# Generated by Django 2.2.10 on 2023-01-20 22:35

from django.db import migrations, models
import django.db.models.deletion
import sinin4.functions
import smart_selects.db_fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contrato', '0001_initial'),
        ('empresa', '0001_initial'),
        ('estado', '0001_initial'),
        ('proyecto', '0001_initial'),
        ('tipo', '0001_initial'),
        ('seguridad_social', '0001_initial'),
        ('parametrizacion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ABMotivoSgi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('estado_descargo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='estadoDescargo_motivosgi', to='estado.Estado')),
            ],
            options={
                'db_table': 'descargo_motivo_sgi',
                'permissions': (('can_see_MotivoSGI', 'can_see_MotivoSGI'),),
            },
        ),
        migrations.CreateModel(
            name='AManiobra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'descargo_maniobra',
                'permissions': (('can_see_Maniobra', 'can_see_Maniobra'),),
            },
        ),
        migrations.CreateModel(
            name='AMotivoInterventor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('motivo_sgi', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='motivosgi_motivointerventor', to='descargo.ABMotivoSgi')),
            ],
            options={
                'db_table': 'descargo_motivo_interventor',
                'permissions': (('can_see_Motivointerventor', 'can_see_Motivointerventor'),),
            },
        ),
        migrations.CreateModel(
            name='ATrabajo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'descargo_trabajo',
                'permissions': (('can_see_Trabajo', 'can_see_Trabajo'),),
            },
        ),
        migrations.CreateModel(
            name='Descargo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_interno', models.CharField(blank=True, max_length=100, null=True)),
                ('numero', models.CharField(max_length=30, null=True)),
                ('barrio', models.CharField(max_length=1000)),
                ('direccion', models.CharField(max_length=1000)),
                ('bdi', models.BooleanField(default=0)),
                ('perdida_mercado', models.BooleanField(default=0)),
                ('area_afectada', models.CharField(max_length=1000)),
                ('elemento_intervenir', models.CharField(max_length=1000)),
                ('fecha', models.DateField()),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('observacion', models.CharField(max_length=4000, null=True)),
                ('observacion_interventor', models.CharField(max_length=4000, null=True)),
                ('correo_bdi', models.FileField(blank=True, null=True, upload_to=sinin4.functions.RandomFileName('descargo/correo_bdi', 'cbdi'))),
                ('soporte_ops', models.FileField(blank=True, null=True, upload_to=sinin4.functions.RandomFileName('descargo/soportes_ops', 'sops'))),
                ('soporte_protocolo', models.FileField(blank=True, null=True, upload_to=sinin4.functions.RandomFileName('descargo/soporte_protocolo', 'spt'))),
                ('lista_chequeo', models.FileField(blank=True, null=True, upload_to=sinin4.functions.RandomFileName('descargo/lista_chequeo', 'lchk'))),
                ('numero_requerimiento', models.CharField(max_length=50, null=True)),
                ('agente_descargo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='empleado_agente', to='seguridad_social.Empleado')),
                ('contratista', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Empresa_Descargo', to='empresa.Empresa')),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Descargo_estado', to='estado.Estado')),
                ('jefe_trabajo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='empleado_jefe', to='seguridad_social.Empleado')),
                ('maniobra', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='maniobra_descargo', to='descargo.AManiobra')),
                ('motivo_interventor', smart_selects.db_fields.ChainedForeignKey(chained_field='motivo_sgi', chained_model_field='motivo_sgi', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='motivointerventor_Descargo', to='descargo.AMotivoInterventor')),
                ('motivo_sgi', smart_selects.db_fields.ChainedForeignKey(chained_field='estado', chained_model_field='estado_descargo', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='motivosgi_Descargo', to='descargo.ABMotivoSgi')),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Descargo_proyecto', to='proyecto.Proyecto')),
                ('trabajo', models.ManyToManyField(to='descargo.ATrabajo')),
            ],
            options={
                'permissions': (('can_see_Descargo', 'can_see_Descargo'),),
            },
        ),
        migrations.CreateModel(
            name='FotoDescargo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ruta', models.ImageField(blank=True, null=True, upload_to=sinin4.functions.RandomFileName('descargo/fotos_descargo', 'dft'))),
                ('regla', models.IntegerField()),
                ('descargo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fotodescargo_descargo', to='descargo.Descargo')),
            ],
            options={
                'permissions': (('can_see_FotoDescargo', 'can_see_FotoDescargo'),),
            },
        ),
        migrations.CreateModel(
            name='Correo_descargo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('apellido', models.CharField(max_length=50)),
                ('correo', models.CharField(max_length=300)),
                ('contratista', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='correoDescargo_contratista', to='empresa.Empresa')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tipo_correoDescargo', to='tipo.Tipo')),
            ],
            options={
                'permissions': (('can_see_Correo_descargo', 'can_see_Correo_descargo'),),
            },
        ),
        migrations.CreateModel(
            name='AIdInternoDescargo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField()),
                ('convenio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contrato_idinternodescargo', to='contrato.Contrato')),
                ('departamento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='idinternodescargo_departamento', to='parametrizacion.Departamento')),
            ],
            options={
                'db_table': 'descargo_id_interno_descargo',
                'permissions': (('can_see_IdInternoDescargo', 'can_see_IdInternoDescargo'),),
            },
        ),
    ]
