# Generated by Django 2.2.10 on 2023-01-30 15:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contrato', '0001_initial'),
        ('correspondencia', '0001_initial'),
        ('parametrizacion', '0001_initial'),
        ('estado', '0001_initial'),
        ('usuario', '0001_initial'),
        ('empresa', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConjuntoEvento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=250)),
            ],
            options={
                'unique_together': {('nombre',)},
            },
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=250)),
                ('valor', models.FloatField()),
                ('conjunto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fk_ConjuntoEvento_conjunto', to='multa.ConjuntoEvento')),
            ],
            options={
                'permissions': (('can_see_eventos', 'can see eventos'),),
                'unique_together': {('nombre', 'conjunto')},
            },
        ),
        migrations.CreateModel(
            name='Solicitud',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consecutivo', models.BigIntegerField(null=True)),
                ('diasApelar', models.BigIntegerField()),
                ('fechaDiligencia', models.DateField(null=True)),
                ('soporte', models.FileField(blank=True, null=True, upload_to='multa')),
                ('valorSolicitado', models.FloatField()),
                ('valorImpuesto', models.FloatField()),
                ('codigoOF', models.CharField(blank=True, max_length=250)),
                ('codigoReferencia', models.CharField(blank=True, max_length=250)),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fk_Contrato_contrato', to='contrato.Contrato')),
                ('correspondenciadescargo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fk_CorrespondenciaEnviada_correspondenciaEnviadaDescargo', to='correspondencia.CorrespondenciaEnviada')),
                ('correspondenciasolicita', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fk_CorrespondenciaEnviada_correspondenciaEnviadaSolicitud', to='correspondencia.CorrespondenciaEnviada')),
                ('firmaImposicion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fk_Funcionario_firmaImposicion', to='parametrizacion.Funcionario')),
            ],
            options={
                'permissions': (('can_see_solicitud', 'can_see_solicitud'), ('can_see_elaborar', 'can see elaborar'), ('can_download_elaborar', 'can download elaborar'), ('can_upload_elaborar', 'can download elaborar'), ('can_delete_elaborar', 'can delete elaborar'), ('can_see_generar', 'can see generar'), ('can_add_generar', 'can add generar'), ('can_see_descargos_sin_pronunciar', 'can see descargos sin pronunciar'), ('can_see_registrar_codigo_of', 'can see registrar codigo of')),
            },
        ),
        migrations.CreateModel(
            name='SolicitudApelacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('comentarios', models.TextField(blank=True)),
                ('fecha_transacion', models.DateTimeField(auto_now_add=True)),
                ('soporte', models.FileField(blank=True, null=True, upload_to='multa-apelacion')),
                ('solicitud', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fk_Solicitud_SolicitudApelacion', to='multa.Solicitud')),
            ],
            options={
                'permissions': (('can_see_solicitudapelacion', 'can_see_solicitudapelacion'),),
            },
        ),
        migrations.CreateModel(
            name='SolicitudSoporte',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=250)),
                ('soporte', models.FileField(null=True, upload_to='multa-solicitud')),
                ('anulado', models.BooleanField(default=False)),
                ('solicitud', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fk_SolicitudSoporte_solicitud', to='multa.Solicitud')),
            ],
            options={
                'permissions': (('can_see_SolicitudSoporte', 'can_see_SolicitudSoporte'),),
            },
        ),
        migrations.CreateModel(
            name='SolicitudPronunciamiento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comentarios', models.TextField(blank=True)),
                ('fecha_transacion', models.DateTimeField(auto_now_add=True)),
                ('apelacion', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='fk_Apelacion_SolicitudPronunciamiento', to='multa.SolicitudApelacion')),
            ],
            options={
                'permissions': (('can_see_solicitudpronunciamiento', 'can_see_solicitudpronunciamiento'),),
            },
        ),
        migrations.CreateModel(
            name='SolicitudHistorial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('soporte', models.FileField(blank=True, null=True, upload_to='multa-historial')),
                ('comentarios', models.TextField(blank=True)),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fk_Estado_SolicitudHistorial', to='estado.Estado')),
                ('solicitud', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fk_Solicitud_SolicitudHistorial', to='multa.Solicitud')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fk_Usuario_SolicitudHistorial', to='usuario.Usuario')),
            ],
        ),
        migrations.CreateModel(
            name='SolicitudConsecutivo',
            fields=[
                ('consecutivo', models.BigIntegerField()),
                ('empresa', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, primary_key=True, related_name='fk_Empresa_Consecutivo', serialize=False, to='empresa.Empresa')),
            ],
            options={
                'unique_together': {('empresa',)},
            },
        ),
        migrations.CreateModel(
            name='SolicitudEvento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numeroimcumplimiento', models.IntegerField()),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fk_Evento_evento', to='multa.Evento')),
                ('solicitud', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fk_Solicitud_SolicitudEvento', to='multa.Solicitud')),
            ],
            options={
                'unique_together': {('evento', 'solicitud')},
            },
        ),
        migrations.CreateModel(
            name='SolicitudEmpresa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('propietario', models.BooleanField(default=False)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fk_Empresa_SolicitudEmpresa', to='empresa.Empresa')),
                ('solicitud', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fk_Solicitud_SolicitudEmpresa', to='multa.Solicitud')),
            ],
            options={
                'permissions': (('can_see_solicitudempresa', 'can_see_solicitudempresa'),),
                'unique_together': {('empresa', 'solicitud', 'propietario'), ('empresa', 'solicitud')},
            },
        ),
    ]
