# Generated by Django 2.2.10 on 2023-01-30 15:30

from django.db import migrations, models
import django.db.models.deletion
import sinin4.functions


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empresa', '0001_initial'),
        ('usuario', '0001_initial'),
        ('tipo', '0001_initial'),
        ('estado', '0001_initial'),
        ('contrato', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AArea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('responsableArea', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fk_solicitud_responsableArea', to='usuario.Usuario')),
            ],
            options={
                'db_table': 'solicitudservicio_area',
                'permissions': (('can_see_area', 'can see area'),),
                'unique_together': {('nombre',)},
            },
        ),
        migrations.CreateModel(
            name='BSolicitud',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaCreacion', models.DateField(auto_now_add=True)),
                ('descripcion', models.CharField(max_length=250)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fk_solicitud_usuarioSolicitante', to='solicitudservicio.AArea')),
                ('contrato', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fk_solicitud_tipo', to='contrato.Contrato')),
                ('empresas', models.ManyToManyField(related_name='fk_solicitud_empresa', to='empresa.Empresa', verbose_name='Empresas que acceden a la solicitud')),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fk_solicitud_estado', to='estado.Estado')),
                ('solicitante', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fk_solicitud_usuarioSolicitante', to='usuario.Usuario')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fk_solicitud_tipo', to='tipo.Tipo')),
            ],
            options={
                'db_table': 'solicitudservicio_solicitud',
                'permissions': (('can_see_solicitudservicio', 'can see solicitudservicio'),),
            },
        ),
        migrations.CreateModel(
            name='CSoportesSolicitud',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaCreacion', models.DateField(auto_now_add=True)),
                ('nombre', models.CharField(default='soporte de la solicitud', max_length=150)),
                ('documento', models.FileField(null=True, upload_to=sinin4.functions.RandomFileName('solicitudservicio/soportes', 'solSer'))),
                ('solicitud', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fk_solicitud_soportes', to='solicitudservicio.BSolicitud')),
            ],
            options={
                'db_table': 'solicitudservicio_soporte',
                'permissions': (('can_see_solicitudserviciosoporte', 'can see solicitudserviciosoporte'),),
            },
        ),
    ]
