# Generated by Django 2.2.10 on 2023-01-30 15:33

from django.db import migrations, models
import django.db.models.deletion
import sinin4.functions


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('giros', '0001_initial'),
        ('empresa', '0001_initial'),
        ('parametrizacion', '0001_initial'),
        ('estado', '0001_initial'),
        ('contrato', '0001_initial'),
        ('tipo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CesionEconomica',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_cuenta', models.CharField(blank=True, max_length=50, null=True)),
                ('motivo_rechazo', models.CharField(blank=True, max_length=100, null=True)),
                ('observacion', models.CharField(blank=True, max_length=100, null=True)),
                ('valor', models.FloatField()),
                ('soporte_tramite', models.FileField(blank=True, null=True, upload_to=sinin4.functions.RandomFileName('cesion_economica/soporte_tramite', 'soporte_tramite'))),
                ('fecha_tramite', models.DateField(auto_now_add=True)),
                ('soporte_enaprobacion', models.FileField(blank=True, null=True, upload_to=sinin4.functions.RandomFileName('cesion_economica/soporte_enaprobacion', 'soporte_enaprobacion'))),
                ('fecha_enaprobacion', models.DateField(blank=True, null=True)),
                ('soporte_aprobado', models.FileField(blank=True, null=True, upload_to=sinin4.functions.RandomFileName('cesion_economica/soporte_aprobado', 'soporte_aprobado'))),
                ('fecha_aprobada', models.DateField(blank=True, null=True)),
                ('banco', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cesion_economica_banco', to='parametrizacion.Banco')),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cesion_economica_contrato', to='contrato.Contrato')),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cesion_economica_estado', to='estado.Estado')),
                ('nombre_giro', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cesion_economica_banco', to='giros.CNombreGiro')),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cesion_economica_proveedor', to='empresa.Empresa')),
                ('tipo_cuenta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cesion_economica_tipo_cuenta', to='tipo.Tipo')),
            ],
            options={
                'verbose_name': 'cesion_economica',
                'db_table': 'cesion_economica',
                'permissions': (('can_see_CesionEconomica', 'can_see_CesionEconomica'),),
            },
        ),
    ]
