# Generated by Django 2.2.10 on 2023-01-20 22:37

from django.db import migrations, models
import django.db.models.deletion
import sinin4.functions


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('proyecto', '0001_initial'),
        ('usuario', '0001_initial'),
        ('tipo', '0001_initial'),
        ('estado', '0001_initial'),
        ('contrato', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aretie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_programada', models.DateField(blank=True, null=True)),
                ('fecha_ejecutada', models.DateField(blank=True, null=True)),
                ('hora', models.TimeField(blank=True, null=True)),
                ('observacion', models.TextField(blank=True, null=True)),
                ('comentario_cancelado', models.TextField(blank=True, null=True)),
                ('estado', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='visita_retie_estado', to='estado.Estado')),
                ('proyecto', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='visita_retie_proyecto', to='proyecto.Proyecto')),
            ],
            options={
                'db_table': 'retie',
                'permissions': (('can_see_retie', 'can see retie'),),
            },
        ),
        migrations.CreateModel(
            name='Soporte',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('soporte', models.FileField(blank=True, null=True, upload_to=sinin4.functions.RandomFileName('retie/soporte', 'vrt'))),
                ('nombre', models.CharField(max_length=100)),
                ('retie', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='soporte_retie', to='seguimiento_retie.Aretie')),
            ],
            options={
                'db_table': 'retie_soporte',
                'permissions': (('can_see_retie_soporte', 'can see retie soporte'),),
            },
        ),
        migrations.CreateModel(
            name='ProyectosNotificados',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enviado', models.BooleanField(default=False)),
                ('fecha', models.DateTimeField(auto_now_add=True, null=True)),
                ('proyecto', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='proyectos_notificados_proyecto', to='proyecto.Proyecto')),
            ],
            options={
                'db_table': 'retie_proyectos_notificados',
                'permissions': (('can_see_proyectos_notificados', 'can see proyectos notificados'),),
            },
        ),
        migrations.CreateModel(
            name='NotificarCorreo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correo', models.CharField(max_length=255)),
                ('nombre', models.CharField(max_length=255)),
                ('notificacion_enviada', models.BooleanField(default=False)),
                ('retie', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='notificar_correo_retie', to='seguimiento_retie.Aretie')),
            ],
            options={
                'db_table': 'retie_notificar_correo',
                'permissions': (('can_see_retie_retie_notificar_correo', 'can see retie retie notificar correo'),),
            },
        ),
        migrations.CreateModel(
            name='NoConformidad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('corregida', models.BooleanField(default=False)),
                ('retie', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='no_conformidad_retie', to='seguimiento_retie.Aretie')),
            ],
            options={
                'db_table': 'retie_no_conformidad',
                'permissions': (('can_see_retie_no_conformidad', 'can see retie no conformidad'),),
            },
        ),
        migrations.CreateModel(
            name='Historial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_programada', models.DateField(blank=True, null=True)),
                ('fecha_ejecutada', models.DateField(blank=True, null=True)),
                ('hora', models.TimeField(blank=True, null=True)),
                ('comentario', models.TextField(blank=True, null=True)),
                ('fecha_ingreso', models.DateTimeField(auto_now_add=True, null=True)),
                ('estado', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='historial_retie_estado', to='estado.Estado')),
                ('retie', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='historial_visita_retie', to='seguimiento_retie.Aretie')),
                ('usuario', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='historial_retie_usuario', to='usuario.Usuario')),
            ],
            options={
                'db_table': 'retie_historial',
                'permissions': (('can_see_retie_historial', 'can see retie historial'),),
            },
        ),
        migrations.CreateModel(
            name='ConfiguracionPorcentajes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('porcentaje', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('comentario', models.TextField(blank=True, null=True)),
                ('contrato', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='configuracion_porcentaje_contrato', to='contrato.Contrato')),
            ],
            options={
                'db_table': 'retie_configuracion_porcentajes',
                'permissions': (('can_see_configuracion_porcentajes', 'can see configuracion porcentajes'),),
            },
        ),
        migrations.CreateModel(
            name='AsistenteVisita',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_asistio', models.BooleanField(default=False)),
                ('notificacion_enviada', models.BooleanField(default=False)),
                ('persona', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='asistente_visita_persona', to='usuario.Persona')),
                ('retie', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='asistente_retie', to='seguimiento_retie.Aretie')),
                ('rol', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='asistente_visita_tipo', to='tipo.Tipo')),
            ],
            options={
                'db_table': 'retie_asistente_visita',
                'permissions': (('can_see_retie_asistente_visita', 'can see retie asistente visita'),),
            },
        ),
    ]
