# Generated by Django 2.2.10 on 2023-01-20 22:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('estado', '0001_initial'),
        ('correspondencia', '0001_initial'),
        ('usuario', '0001_initial'),
        ('empresa', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CorrespondenciaRecibida',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('radicado', models.BigIntegerField()),
                ('fechaRecibida', models.DateField()),
                ('anoRecibida', models.BigIntegerField()),
                ('remitente', models.CharField(max_length=250, null=True)),
                ('asunto', models.TextField(blank=True)),
                ('fechaRegistro', models.DateTimeField(auto_now_add=True)),
                ('privado', models.BooleanField(default=False)),
                ('radicadoPrevio', models.CharField(blank=True, max_length=250)),
                ('fechaRespuesta', models.DateField(blank=True, null=True)),
                ('correspondenciaEnviada', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fk_CorrespondenciaRecibida_correspondenciaEnviada', to='correspondencia.CorrespondenciaEnviada')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fk_CorrespondenciaRecibida_empresa_Empresa', to='empresa.Empresa')),
                ('usuarioSolicitante', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fk_CorrespondenciaRecibida_usuarioSolicitante_Usuario', to='usuario.Usuario')),
            ],
            options={
                'permissions': (('can_see_CorrespondenciaRecibida', 'can_see_CorrespondenciaRecibida'),),
                'unique_together': {('empresa', 'radicado', 'anoRecibida')},
            },
        ),
        migrations.CreateModel(
            name='CorrespondenciaRecibidaSoporte',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=250, null=True)),
                ('soporte', models.FileField(null=True, upload_to='correspondencia_recibida')),
                ('anulado', models.BooleanField(default=False)),
                ('correspondencia', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fk_CorrespondenciaRecibidaSoporte_correspondencia', to='correspondencia_recibida.CorrespondenciaRecibida')),
            ],
            options={
                'permissions': (('can_see_CorrespondenciaRecibidaSoporte', 'can_see_CorrespondenciaRecibidaSoporte'),),
            },
        ),
        migrations.CreateModel(
            name='CorrespondenciaRecibidaAsignada',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaAsignacion', models.DateTimeField(auto_now_add=True)),
                ('copia', models.BooleanField(default=False)),
                ('correspondenciaRecibida', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fk_CorrespondenciaRecibidaAsignada_correspondencia', to='correspondencia_recibida.CorrespondenciaRecibida')),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fk_CorrespondenciaRecibidaAsignada_estado', to='estado.Estado')),
                ('respuesta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fk_CorrespondenciaRecibidaAsignada_correspondenciaEnviada', to='correspondencia.CorrespondenciaEnviada')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fk_CorrespondenciaRecibidaAsignada_usuario', to='usuario.Usuario')),
            ],
            options={
                'permissions': (('can_see_CorrespondenciaRecibidaAsignada', 'can_see_CorrespondenciaRecibidaAsignada'),),
            },
        ),
    ]
