# Generated by Django 2.2.10 on 2023-01-20 22:32

from django.db import migrations, models
import django.db.models.deletion
import sinin4.functions


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('correspondencia', '__first__'),
        ('financiero', '__first__'),
        ('estado', '0001_initial'),
        ('parametrizacion', '0001_initial'),
        ('empresa', '0001_initial'),
        ('contrato', '__first__'),
        ('tipo', '0001_initial'),
        ('factura', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='CNombreGiro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='nombre_giro_contrato', to='contrato.Contrato')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='nombre_giro_tipo', to='tipo.Tipo')),
            ],
            options={
                'verbose_name': 'Nombre giros',
                'db_table': 'giros_nombre_giro',
                'permissions': (('can_see_cnombregiro', 'can_see_cnombregiro'),),
            },
        ),
        migrations.CreateModel(
            name='DEncabezadoGiro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('soporte', models.FileField(blank=True, null=True, upload_to=sinin4.functions.RandomFileName('giros/encabezado_giro', 'plz'))),
                ('referencia', models.CharField(blank=True, max_length=50)),
                ('num_causacion', models.CharField(blank=True, max_length=100)),
                ('fecha_conta', models.DateField(blank=True, null=True)),
                ('disparar_flujo', models.BooleanField(default=False)),
                ('numero_radicado', models.CharField(blank=True, max_length=100)),
                ('comentario', models.CharField(blank=True, max_length=500)),
                ('flujo_test', models.BooleanField(default=0)),
                ('texto_documento_sap', models.CharField(blank=True, max_length=500)),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='encabezado_contrato', to='contrato.Contrato')),
                ('nombre', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='encabezado_nombre_giro', to='giros.CNombreGiro')),
                ('pago_recurso', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='encabezado_tipo_pago', to='tipo.Tipo')),
            ],
            options={
                'verbose_name': 'Encabezado giros',
                'db_table': 'giros_encabezado_giro',
                'permissions': (('can_see_dencabezadogiro', 'can_see_dencabezadogiro'), ('can_see_detalle', 'can_see_detalle'), ('can_see_reporte', 'can_see_reporte'), ('can_see_seguimiento', 'can_see_seguimiento'), ('can_see_actualizar_tipo_pago', 'can_see_actualizar_tipo_pago'), ('can_see_disparar_flujo', 'can_see_disparar_flujo'), ('can_see_sol_giros', 'can_see_sol_giros'), ('can_see_registro_consulta_referencia', 'can_see_registro_consulta_referencia'), ('can_see_sol_giros_sin_revisar', 'can_see_sol_giros_sin_revisar'), ('can_see_sol_giros_test_op', 'can_see_sol_giros_test_op'), ('can_see_sol_giros_por_pagar', 'can_see_sol_giros_por_pagar'), ('can_see_sol_giros_pagos_rechazados', 'can_see_sol_giros_pagos_rechazados')),
            },
        ),
        migrations.CreateModel(
            name='DetalleGiro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_cuenta', models.CharField(max_length=30)),
                ('valor_girar', models.FloatField()),
                ('fecha_pago', models.DateField(blank=True, null=True)),
                ('test_op', models.CharField(blank=True, max_length=150)),
                ('fecha_pago_esperada', models.DateField(blank=True, null=True)),
                ('codigo_pago', models.CharField(blank=True, max_length=50, null=True)),
                ('soporte_consecutivo_desabilitado', models.FileField(blank=True, null=True, upload_to=sinin4.functions.RandomFileName('giros/consecutivo_desahabilitado', 'plz'))),
                ('fecha_transaccion_test', models.DateField(blank=True, null=True)),
                ('banco', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='detalle_banco', to='parametrizacion.Banco')),
                ('carta_autorizacion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='FK_giros_detalle_giro_correspondencia_correspondenciaenviada', to='correspondencia.CorrespondenciaEnviada')),
                ('cesion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='detalle_giro_cesion', to='factura.Cesion')),
                ('contratista', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='detalle_empresa', to='empresa.Empresa')),
                ('cruce', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='detalle_giro_compensacion', to='factura.Compensacion')),
                ('cuenta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='detalle_cuenta', to='financiero.FinancieroCuenta')),
                ('encabezado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='detalle_encabezado_giro', to='giros.DEncabezadoGiro')),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='detalle_estado', to='estado.Estado')),
                ('tipo_cuenta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='detalle_tipo', to='tipo.Tipo')),
            ],
            options={
                'db_table': 'giros_detalle_giro',
                'permissions': (('can_see_detallegiro', 'can_see_detallegiro'), ('can_see_autorizar', 'can_see_autorizar'), ('can_see_desautorizar', 'can_see_desautorizar'), ('can_see_pagar', 'can_see_pagar'), ('can_see_reversar', 'can_see_reversar')),
            },
        ),
        migrations.CreateModel(
            name='RechazoGiro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(blank=True, null=True)),
                ('motivo', models.CharField(blank=True, max_length=150, null=True)),
                ('atendido', models.BooleanField(blank=True, default=0)),
                ('detalle', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='detalle_rechazo_giro', to='giros.DetalleGiro')),
            ],
            options={
                'db_table': 'giros_rechazo',
                'permissions': (('can_see_girosrechazo', 'can_see_girosrechazo'),),
            },
        ),
    ]
