# Generated by Django 2.2.10 on 2023-01-20 22:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empresa', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sessions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cedula', models.BigIntegerField(unique=True)),
                ('nombres', models.CharField(max_length=255)),
                ('apellidos', models.CharField(max_length=255)),
                ('correo', models.EmailField(blank=True, max_length=70, null=True)),
                ('telefono', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'ordering': ['nombres', 'apellidos'],
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ImageField(blank=True, default='usuario/default.jpg', null=True, upload_to='usuario')),
                ('iniciales', models.CharField(max_length=5)),
                ('cantidad_sesiones', models.IntegerField(blank=True, default=1, null=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Empresa_usuario', to='empresa.Empresa')),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='persona_usuario', to='usuario.Persona')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserSession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Sesion', to='sessions.Session')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='logged_in_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
