# Generated by Django 2.2.10 on 2023-01-20 22:31

from django.db import migrations, models
import django.db.models.deletion
import sinin4.functions


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tipo', '0001_initial'),
        ('estado', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nit', models.CharField(max_length=255, unique=True)),
                ('nombre', models.CharField(max_length=255)),
                ('direccion', models.CharField(max_length=255)),
                ('logo', models.ImageField(blank=True, default='empresa/default.jpg', null=True, upload_to=sinin4.functions.RandomFileName('empresa/soporte', 'logo'))),
                ('esDisenador', models.BooleanField(default=False)),
                ('esProveedor', models.BooleanField(default=False)),
                ('esContratista', models.BooleanField(default=False)),
                ('esContratante', models.BooleanField(default=False)),
                ('encabezado', models.ImageField(blank=True, default='empresa/default.jpg', null=True, upload_to=sinin4.functions.RandomFileName('empresa/soporte', 'enca'))),
                ('piePagina', models.ImageField(blank=True, default='empresa/default.jpg', null=True, upload_to=sinin4.functions.RandomFileName('empresa/soporte', 'pie'))),
                ('marcaAgua', models.ImageField(blank=True, default='empresa/default.jpg', null=True, upload_to=sinin4.functions.RandomFileName('empresa/soporte', 'agua'))),
                ('peso', models.FloatField(blank=True, null=True)),
                ('consecutivoDigitado', models.BooleanField(default=False)),
                ('abreviatura', models.CharField(blank=True, max_length=255, null=True)),
                ('control_pago_factura', models.BooleanField(default=False)),
                ('codigo_acreedor', models.IntegerField(blank=True, null=True)),
                ('tipo_letra', models.CharField(blank=True, max_length=255)),
                ('tam_letra_consecutivo', models.IntegerField(null=True)),
                ('tam_letra_iniciales', models.IntegerField(null=True)),
                ('tam_letra_elaboro', models.IntegerField(null=True)),
                ('tam_letra_referencia', models.IntegerField(null=True)),
                ('tam_letra_contenido', models.IntegerField(null=True)),
            ],
            options={
                'ordering': ['nombre'],
                'permissions': (('can_see', 'can see'),),
            },
        ),
        migrations.CreateModel(
            name='EmpresaCuenta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entidad_bancaria', models.CharField(blank=True, max_length=255)),
                ('numero_cuenta', models.CharField(blank=True, max_length=255)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fk_EmpresaCuenta_empresa', to='empresa.Empresa')),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fk_EmpresaCuenta_estado', to='estado.Estado')),
                ('tipo_cuenta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tipo_cuenta_empresa', to='tipo.Tipo')),
            ],
            options={
                'db_table': 'empresa_cuenta',
                'permissions': (('can_see_empresa_cuenta', 'can_see_empresa_cuenta'), ('can_see_empresa_cuentaEstado', 'can_see_empresa_cuentaEstado')),
            },
        ),
        migrations.CreateModel(
            name='EmpresaContratante',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fk_EmpresaContratante_empresa', to='empresa.Empresa')),
                ('empresa_ver', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fk_EmpresaContratante_empresa_ver', to='empresa.Empresa')),
            ],
            options={
                'db_table': 'empresa_contratante',
                'unique_together': {('empresa', 'empresa_ver')},
            },
        ),
        migrations.CreateModel(
            name='EmpresaAcceso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fk_EmpresaAcceso_empresa', to='empresa.Empresa')),
                ('empresa_ver', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fk_EmpresaAcceso_empresa_ver', to='empresa.Empresa')),
            ],
            options={
                'unique_together': {('empresa', 'empresa_ver')},
            },
        ),
    ]
