# Generated by Django 2.2.10 on 2023-01-30 15:30

from django.db import migrations, models
import django.db.models.deletion
import coasmedas.functions


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('estado', '0001_initial'),
        ('tipo', '0001_initial'),
        ('usuario', '0001_initial'),
        ('proyecto', '0001_initial'),
        ('contrato', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ASolicita',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'solicita',
                'db_table': 'control_cambios_solicita',
                'permissions': (('can_see_solicita', 'can_see_solicita'),),
            },
        ),
        migrations.CreateModel(
            name='BUnidadConstructiva',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(blank=True, max_length=50, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('valor_mano_obra', models.FloatField()),
                ('valor_materiales', models.FloatField()),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='UnidadConstructiva_contrato', to='contrato.Contrato')),
                ('proyecto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='UnidadConstructiva_proyecto', to='proyecto.Proyecto')),
            ],
            options={
                'verbose_name': 'Unidades Constructivas',
                'db_table': 'control_cambios_unidad_constructiva',
                'permissions': (('can_see_UnidadConstructiva', 'can_see_UnidadConstructiva'),),
            },
        ),
        migrations.CreateModel(
            name='CCambio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(blank=True, null=True)),
                ('numero_cambio', models.IntegerField(blank=True, null=True)),
                ('motivo', models.TextField(blank=True, null=True)),
                ('solicitud_enviada', models.BooleanField(default=False)),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cambio_proyecto', to='proyecto.Proyecto')),
                ('solicita', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cambio_solicita', to='control_cambios.ASolicita')),
                ('tipo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cambio_tipo', to='tipo.Tipo')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cambio_usuario', to='usuario.Usuario')),
                ('usuario_revisa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cambio_usuarioRevisa', to='usuario.Usuario')),
            ],
            options={
                'verbose_name': 'Cambio',
                'db_table': 'control_cambios_cambio',
                'permissions': (('can_see_cambio', 'can_see_cambio'),),
            },
        ),
        migrations.CreateModel(
            name='DMaterial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(blank=True, max_length=50, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('unidad', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'verbose_name': 'Material',
                'db_table': 'control_cambios_material',
                'permissions': (('can_see_material', 'can_see_material'),),
            },
        ),
        migrations.CreateModel(
            name='GSoporte',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('ruta', models.FileField(blank=True, null=True, upload_to=coasmedas.functions.RandomFileName('control_cambios/Soporte_ruta', 'plz'))),
                ('cambio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Soporte_cambio', to='control_cambios.CCambio')),
            ],
            options={
                'verbose_name': 'Soporte',
                'db_table': 'control_cambios_soporte',
                'permissions': (('can_see_Soporte', 'can_see_Soporte'),),
            },
        ),
        migrations.CreateModel(
            name='FCambioProyecto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.FloatField()),
                ('comentario', models.TextField(blank=True, null=True)),
                ('cambio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='CambioProyecto_cambio', to='control_cambios.CCambio')),
                ('estado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='estado.Estado')),
                ('uucc', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='CambioProyecto_uucc', to='control_cambios.BUnidadConstructiva')),
            ],
            options={
                'verbose_name': 'Cambio proyecto',
                'db_table': 'control_cambios_cambio_proyecto',
                'permissions': (('can_see_CambioProyecto', 'can_see_CambioProyecto'),),
            },
        ),
        migrations.CreateModel(
            name='EUUCCMaterial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.FloatField()),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='UnidadConstructiva_material', to='control_cambios.DMaterial')),
                ('uucc', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='UnidadConstructiva_UnidadConstructiva', to='control_cambios.BUnidadConstructiva')),
            ],
            options={
                'verbose_name': 'UUCC Materiales',
                'db_table': 'control_cambios_uucc_material',
                'permissions': (('can_see_UUCCMateriales', 'can_see_UUCCMateriales'),),
            },
        ),
    ]
