from django.conf.urls import url

from . import views


urlpatterns = [
  	url(r'^index/$', views.gestion_proyecto, name='gestion_proyecto.gestion_proyecto'),
  	url(r'^opciones/$', views.opciones, name='gestion_proyecto.opciones'),
  	url(r'^fondo/$', views.fondo, name='gestion_proyecto.fondo'),
  	url(r'^eliminar_fondos/$', views.eliminar_fondos, name='gestion_proyecto.eliminar_fondos'),
  	url(r'^cambio_estado/$', views.cambio_estado, name='gestion_proyecto.cambio_estado'),
  	url(r'^export_excel_fondo/$', views.export_excel_fondo, name='gestion_proyecto.export_excel_fondo'),
  	url(r'^disenadores/$', views.disenadores, name='gestion_proyecto.disenadores'),  	
  	url(r'^incluir_disenadores/$', views.incluir_disenadores, name='gestion_proyecto.incluir_disenadores'),
  	url(r'^quitar_disenadores/$', views.quitar_disenadores, name='gestion_proyecto.quitar_disenadores'),
  	url(r'^datos_diseno/$', views.datos_diseno, name='gestion_proyecto.datos_diseno'),
  	url(r'^eliminar_datos_disenos/$', views.eliminar_datos_disenos, name='gestion_proyecto.eliminar_datos_disenos'),  	
    url(r'^actualizar_orden/$', views.actualizar_orden, name='gestion_proyecto.actualizar_orden'),  
    url(r'^campana/$', views.campana, name='gestion_proyecto.campana'),    
    url(r'^eliminar_campanas/$', views.eliminar_campanas, name='gestion_proyecto.eliminar_campanas'),    
    url(r'^documentos/(?P<id_campana>[0-9]+)/$', views.documentos, name='gestion_proyecto.documentos'),   
    url(r'^clonar_campana/$', views.clonar_campana, name='gestion_proyecto.clonar_campana'),  
    url(r'^campana_empresa/(?P<id_campana>[0-9]+)/$', views.campana_empresa, name='gestion_proyecto.campana_empresa'),  
    url(r'^incluir_empresas/$', views.incluir_empresas, name='gestion_proyecto.incluir_empresas'),  
    url(r'^quitar_empresas/$', views.quitar_empresas, name='gestion_proyecto.quitar_empresas'),  
    url(r'^solicitante/$', views.solicitante, name='gestion_proyecto.solicitante'),  
    url(r'^eliminar_solicitantes/$', views.eliminar_solicitantes, name='gestion_proyecto.eliminar_solicitantes'), 
    url(r'^export_excel_solicitante/$', views.export_excel_solicitante, name='gestion_proyecto.export_excel_solicitante'), 
    url(r'^permisos/$', views.permisos, name='gestion_proyecto.permisos'),  
    url(r'^diseno/$', views.diseno, name='gestion_proyecto.diseno'),
    url(r'^deshabilitardiseno/$', views.deshabilitardiseno, name='gestion_proyecto.deshabilitardiseno'),
    url(r'^tablero/(?P<version_diseno_id>[0-9]+)/$', views.tablero, name='gestion_proyecto.tablero'),
    url(r'^solicitudes/$', views.solicitudes, name='gestion_proyecto.solicitudes'),    
    url(r'^eliminar_solicitudes/$', views.eliminar_solicitudes, name='gestion_proyecto.eliminar_solicitudes'),     
    url(r'^solicitud_diseno/(?P<id_solicitud>[0-9]+)/$', views.solicitud_diseno, name='gestion_proyecto.solicitud_diseno'),
    url(r'^agregar_solicitudes/$', views.agregar_solicitudes, name='gestion_proyecto.agregar_solicitudes'),
    url(r'^mapa/$', views.mapa, name='gestion_proyecto.mapa'),
    url(r'^actualizar_fechas/$', views.actualizar_fechas, name='gestion_proyecto.actualizar_fechas'),
    url(r'^actualizar_info/$', views.actualizar_info, name='gestion_proyecto.actualizar_info'),
    url(r'^export_excel_diseno/$', views.export_excel_diseno, name='gestion_proyecto.export_excel_diseno'),
    url(r'^export_excel_convocatoria/$', views.export_excel_convocatoria, name='gestion_proyecto.export_excel_convocatoria'),
    url(r'^eliminar_puntos/$', views.eliminar_puntos, name='gestion_proyecto.eliminar_puntos'),
    url(r'^descargar_plantilla/$', views.descargar_plantilla, name='gestion_proyecto.descargar_plantilla'),
    url(r'^mapa_grande/(?P<id_diseno>[0-9]+)/$', views.mapa_grande, name='gestion_proyecto.mapa_grande'),
    url(r'^guardar_puntos_soporte/$', views.guardar_puntos_soporte, name='gestion_proyecto.guardar_puntos_soporte'),    
    url(r'^guardar_permisos/$', views.guardar_permisos, name='gestion_proyecto.guardar_permisos'),
    url(r'^cantidades_estado/$', views.cantidades_estado, name='gestion_proyecto.cantidades_estado'),
    url(r'^reportar_reporte_diseno/$', views.reportar_reporte_diseno, name='gestion_proyecto.reportar_reporte_diseno'),
    url(r'^reportar_reporte_exitoso/$', views.reportar_reporte_exitoso, name='gestion_proyecto.reportar_reporte_exitoso'),
    url(r'^reportar_insconsistencia/$', views.reportar_insconsistencia, name='gestion_proyecto.reportar_insconsistencia'),
    url(r'^version_diseno/(?P<id_diseno>[0-9]+)/$', views.version_diseno, name='gestion_proyecto.version_diseno'),
    url(r'^eliminar_versiones/$', views.eliminar_versiones, name='gestion_proyecto.eliminar_versiones'),  
    url(r'^consultar_tablero/$', views.consultar_tablero, name='gestion_proyecto.consultar_tablero'),  
    url(r'^ver-soporte/$', views.VerSoporte, name='gestion_proyecto.VerSoporte'),  
    url(r'^ver-soporte-solicitud/$', views.VerSoporteSolicitud, name='gestion_proyecto.VerSoporteSolicitud'),  
]