# Generated by Django 2.2.10 on 2023-01-20 22:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('app', models.CharField(max_length=250)),
                ('color', models.CharField(blank=True, max_length=250)),
                ('icono', models.CharField(blank=True, max_length=250)),
                ('estado', models.BooleanField(default=1)),
                ('codigo', models.IntegerField(blank=True, null=True)),
                ('orden', models.IntegerField()),
            ],
            options={
                'unique_together': {('app', 'codigo')},
            },
        ),
        migrations.CreateModel(
            name='Estados_posibles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actual', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='f_Estado_estado', to='estado.Estado')),
                ('siguiente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='f_Estado_estado_2', to='estado.Estado')),
            ],
        ),
    ]
