# Generated by Django 2.2.10 on 2023-01-30 15:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuario', '0001_initial'),
        ('estado', '0001_initial'),
        ('empresa', '0001_initial'),
        ('parametrizacion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ACampana',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'gestion_proyecto_campana',
                'permissions': (('can_see_acampana', 'can see acampana'),),
            },
        ),
        migrations.CreateModel(
            name='AFondo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fondo_empresa', to='empresa.Empresa')),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fondo_estado', to='estado.Estado')),
            ],
            options={
                'db_table': 'gestion_proyecto_fondo',
                'permissions': (('can_see_afondo', 'can see afondo'),),
            },
        ),
        migrations.CreateModel(
            name='ASolicitante',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'gestion_proyecto_solicitante',
                'permissions': (('can_see_asolicitante', 'can see asolicitante'),),
            },
        ),
        migrations.CreateModel(
            name='AUnidadMedida',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'gestion_proyecto_documento_unidad_medida',
            },
        ),
        migrations.CreateModel(
            name='CSolicitud',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('fecha', models.DateField()),
                ('entidad', models.CharField(blank=True, max_length=250, null=True)),
                ('visita', models.BooleanField(default=False)),
                ('fecha_visita', models.DateField(blank=True, null=True)),
                ('fecha_respuesta', models.DateField(blank=True, null=True)),
                ('descripcion_visita', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'gestion_proyecto_solicitud',
                'permissions': (('can_see_solicitud', 'can see solicitud'),),
            },
        ),
        migrations.CreateModel(
            name='DatoDiseno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('orden', models.IntegerField()),
                ('unidad_medida', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dato_diseno_unidad_medida', to='gestion_proyecto.AUnidadMedida')),
            ],
            options={
                'db_table': 'gestion_proyecto_dato_diseno',
                'permissions': (('can_see_datodiseno', 'can see datodiseno'),),
            },
        ),
        migrations.CreateModel(
            name='Diseno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('activado', models.BooleanField(default=True)),
                ('costo_proyecto', models.BigIntegerField()),
                ('costo_diseno', models.BigIntegerField()),
                ('campana', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='diseno_campana', to='gestion_proyecto.ACampana')),
                ('disenadores', models.ManyToManyField(blank=True, related_name='diseno_disenadores', to='empresa.Empresa')),
                ('fondo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='diseno_fondo', to='gestion_proyecto.AFondo')),
                ('municipio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='diseno_municipio', to='parametrizacion.Municipio')),
                ('propietaria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='diseno_empresa', to='empresa.Empresa')),
                ('solicitante', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='diseno_solicitante', to='gestion_proyecto.ASolicitante')),
                ('solicitudes', models.ManyToManyField(blank=True, related_name='diseno_solicitudes', to='gestion_proyecto.CSolicitud')),
            ],
            options={
                'db_table': 'gestion_proyecto_diseno',
                'permissions': (('can_see_diseno', 'can see diseno'), ('can_see_reportar_diseno', 'can see reportar_diseno'), ('can_see_revision_diseno', 'can see revision_diseno')),
            },
        ),
        migrations.CreateModel(
            name='DocumentoEstado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('campana', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documento_campana', to='gestion_proyecto.ACampana')),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documento_estado', to='estado.Estado')),
            ],
            options={
                'db_table': 'gestion_proyecto_documento_estado',
                'permissions': (('can_see_documentoestado', 'can see documentoestado'),),
            },
        ),
        migrations.CreateModel(
            name='DVersionesDiseno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('fecha', models.DateField(auto_now_add=True, null=True)),
                ('reportar_diseno', models.BooleanField(default=False)),
                ('reportar_satisfaccion', models.BooleanField(default=False)),
                ('diseno', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='versiones_diseno', to='gestion_proyecto.Diseno')),
                ('estado_reporte', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='diseno_reporte', to='estado.Estado')),
            ],
            options={
                'db_table': 'gestion_proyecto_version_diseno',
                'permissions': (('can_see_dversionesdiseno', 'can see dversionesdiseno'),),
            },
        ),
        migrations.CreateModel(
            name='EstadoDiseno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('diseno', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='estado_diseno', to='gestion_proyecto.Diseno')),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='estado_diseno_estado', to='estado.Estado')),
                ('version_diseno', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='estado_version_diseno', to='gestion_proyecto.DVersionesDiseno')),
            ],
            options={
                'db_table': 'gestion_proyecto_estado_diseno',
                'permissions': (('can_see_estado_diseno', 'can see estado_diseno'),),
            },
        ),
        migrations.CreateModel(
            name='SoporteEstado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('fecha', models.DateField(auto_now_add=True, null=True)),
                ('ruta', models.FileField(blank=True, null=True, upload_to='gestion_diseno_estado')),
                ('documento_estado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='soporte_estado_documento_estado', to='gestion_proyecto.DocumentoEstado')),
                ('estado_diseno', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='soporte_estado_estado_diseno', to='gestion_proyecto.EstadoDiseno')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='soporte_estado_usuario', to='usuario.Usuario')),
            ],
            options={
                'db_table': 'gestion_proyecto_soporte_estado',
            },
        ),
        migrations.CreateModel(
            name='TComentarioDiseno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comentario', models.TextField()),
                ('fecha', models.DateTimeField(auto_now_add=True, null=True)),
                ('diseno', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='comentario_diseno', to='gestion_proyecto.Diseno')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='comentario_diseno_usuario', to='usuario.Usuario')),
                ('version_diseno', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='comentarios_version_diseno', to='gestion_proyecto.DVersionesDiseno')),
            ],
            options={
                'db_table': 'gestion_proyecto_comentario',
            },
        ),
        migrations.CreateModel(
            name='SoporteSolicitud',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('fecha', models.DateField()),
                ('ruta', models.FileField(blank=True, null=True, upload_to='gestion_diseno_solicitud')),
                ('solicitud', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='soporte_solicitud_solicitud', to='gestion_proyecto.CSolicitud')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='soporte_solicitud_usuario', to='usuario.Usuario')),
            ],
            options={
                'db_table': 'gestion_proyecto_soporte_solicitud',
            },
        ),
        migrations.CreateModel(
            name='SoporteEstadoComentario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comentario', models.TextField()),
                ('fecha', models.DateTimeField(auto_now_add=True, null=True)),
                ('soporte_estado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='soporte_comentario_soporte_estado', to='gestion_proyecto.SoporteEstado')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='soporte_comentario_usuario', to='usuario.Usuario')),
            ],
            options={
                'db_table': 'gestion_proyecto_soporte_comentario',
                'permissions': (('can_see_comentario_soporte', 'can see comentario_soporte'),),
            },
        ),
        migrations.CreateModel(
            name='PermisoDiseno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consultar', models.BooleanField(default=False)),
                ('editar', models.BooleanField(default=False)),
                ('diseno', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='permiso_diseno_diseno', to='gestion_proyecto.Diseno')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='permiso_diseno_empresa', to='empresa.Empresa')),
            ],
            options={
                'db_table': 'gestion_proyecto_permiso_diseno',
                'permissions': (('can_see_permiso_diseno', 'can see permiso_diseno'),),
            },
        ),
        migrations.CreateModel(
            name='MapaDiseno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('longitud', models.TextField()),
                ('latitud', models.TextField()),
                ('diseno', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mapa_diseno', to='gestion_proyecto.Diseno')),
                ('version_diseno', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mapa_version_diseno', to='gestion_proyecto.DVersionesDiseno')),
            ],
            options={
                'db_table': 'gestion_proyecto_mapa_diseno',
                'permissions': (('can_see_mapa_diseno', 'can see mapa_diseno'),),
            },
        ),
        migrations.CreateModel(
            name='InfoDiseno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.FloatField()),
                ('dato_diseno', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='informacion_dato_diseno', to='gestion_proyecto.DatoDiseno')),
                ('diseno', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='informacion_diseno', to='gestion_proyecto.Diseno')),
                ('version_diseno', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='informacion_version_diseno', to='gestion_proyecto.DVersionesDiseno')),
            ],
            options={
                'db_table': 'gestion_proyecto_info_diseno',
                'permissions': (('can_see_info_diseno', 'can see info_diseno'),),
            },
        ),
        migrations.CreateModel(
            name='CampanaEmpresa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('propietario', models.BooleanField(default=False)),
                ('campana', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='campana_estado_campana', to='gestion_proyecto.ACampana')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='campana_estado_empresa', to='empresa.Empresa')),
            ],
            options={
                'db_table': 'gestion_proyecto_campana_empresa',
                'permissions': (('can_see_campana_empresa', 'can see campana_empresa'),),
            },
        ),
    ]
