# Generated by Django 2.2.10 on 2023-01-20 22:40

from django.db import migrations, models
import django.db.models.deletion
import coasmedas.functions


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('estado', '0001_initial'),
        ('usuario', '0001_initial'),
        ('proyecto', '0001_initial'),
        ('tipo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AEquipo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.TextField()),
                ('descripcion', models.TextField()),
                ('usuario_administrador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='equipo_usuario_administrador', to='usuario.Usuario')),
                ('usuario_responsable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='equipo_usuario_responsable', to='usuario.Usuario')),
            ],
            options={
                'db_table': 'administrador_tarea_equipo',
            },
        ),
        migrations.CreateModel(
            name='Colaborador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='colaborador_equipo', to='administrador_tarea.AEquipo')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='colaborador_usuario', to='usuario.Usuario')),
            ],
            options={
                'db_table': 'administrador_tarea_colaborador',
            },
        ),
        migrations.CreateModel(
            name='DTarea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asunto', models.TextField()),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('fecha_fin', models.DateField(null=True)),
                ('numero', models.TextField(blank=True, null=True)),
                ('colaborador_actual', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tarea_colaborador', to='administrador_tarea.Colaborador')),
                ('proyecto', models.ManyToManyField(blank=True, related_name='tarea_proyecto', to='proyecto.Proyecto')),
                ('tipo_tarea', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tarea_tipo', to='tipo.Tipo')),
                ('usuario_responsable', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tarea_usuario', to='usuario.Usuario')),
            ],
            options={
                'db_table': 'administrador_tarea_tarea',
            },
        ),
        migrations.CreateModel(
            name='DTareaAsignacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('comentario', models.TextField(blank=True, null=True)),
                ('colaborador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='asignacion_colaborador', to='administrador_tarea.Colaborador')),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='asignacion_estado', to='estado.Estado')),
                ('solicitante', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='asignacion_usuario', to='usuario.Usuario')),
                ('tarea', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='asignacion_tarea', to='administrador_tarea.DTarea')),
            ],
            options={
                'db_table': 'administrador_tarea_asignacion_tarea',
            },
        ),
        migrations.CreateModel(
            name='TareaActividad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asunto', models.TextField()),
                ('fecha', models.DateTimeField()),
                ('fecha_transaccion', models.DateField()),
                ('lugar', models.TextField()),
                ('solicitante', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='actividad_usuario', to='usuario.Usuario')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='actividad_tipo', to='tipo.Tipo')),
                ('usuario_inivitado', models.ManyToManyField(blank=True, related_name='actividad_usuario_invitado', to='usuario.Usuario')),
            ],
            options={
                'db_table': 'administrador_tarea_actividad',
            },
        ),
        migrations.CreateModel(
            name='TareaActividadSoporte',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.TextField()),
                ('ruta', models.FileField(blank=True, null=True, upload_to=coasmedas.functions.RandomFileName('tarea/soporte_actividad', 'ta'))),
                ('tarea_actividad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='actividad_soporte', to='administrador_tarea.TareaActividad')),
            ],
            options={
                'db_table': 'administrador_tarea_actividad_soporte',
            },
        ),
        migrations.CreateModel(
            name='SoporteAsignacionTarea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.TextField()),
                ('ruta', models.FileField(blank=True, null=True, upload_to=coasmedas.functions.RandomFileName('tarea/soporte_tarea', 'tt'))),
                ('asignacion_tarea', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='soporte_asignacion', to='administrador_tarea.DTareaAsignacion')),
            ],
            options={
                'db_table': 'administrador_tarea_soporte_asignacion_tarea',
            },
        ),
        migrations.CreateModel(
            name='DTareaComentario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comentario', models.TextField()),
                ('fecha', models.DateTimeField(blank=True, null=True)),
                ('tarea', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='comentario_tarea', to='administrador_tarea.DTarea')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='comentario_tarea_usuario', to='usuario.Usuario')),
            ],
            options={
                'db_table': 'administrador_tarea_comentario',
            },
        ),
    ]
