# Generated by Django 2.2.10 on 2023-01-30 15:33

import colorfield.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuario', '0001_initial'),
        ('empresa', '0001_initial'),
        ('proyecto', '0001_initial'),
        ('contrato', '0001_initial'),
        ('estado', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='APeriodicidadG',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('numero_dias', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Periodicidad',
                'db_table': 'avanceObraGrafico2_periodicidad',
                'permissions': (('can_see_periodicidadgrafico', 'can see periodicidadgrafico'),),
                'unique_together': {('nombre',)},
            },
        ),
        migrations.CreateModel(
            name='BEsquemaCapitulosG',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('macrocontrato', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='esquema_contrato_grafico', to='contrato.Contrato')),
            ],
            options={
                'verbose_name': 'Esquemas',
                'db_table': 'avanceObraGrafico2_esquemaCapitulos',
                'permissions': (('can_see_esquemacapitulosgrafico', 'can see esquemacapitulosgrafico'),),
            },
        ),
        migrations.CreateModel(
            name='CatalogoUnidadConstructiva',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('ano', models.IntegerField()),
                ('activo', models.BooleanField(default=True)),
                ('mcontrato', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='catalogo_contrato', to='contrato.Contrato')),
            ],
            options={
                'verbose_name': 'Catalogo de Unidades Constructivas',
                'db_table': 'avanceObraGrafico2_catalogo',
                'permissions': (('can_see_catalogo', 'can see catalogo'),),
            },
        ),
        migrations.CreateModel(
            name='CEsquemaCapitulosActividadesG',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('nivel', models.IntegerField()),
                ('padre', models.IntegerField()),
                ('peso', models.FloatField()),
                ('esquema', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='actividades_esquemagrafico', to='avanceObraGrafico2.BEsquemaCapitulosG')),
            ],
            options={
                'verbose_name': 'Capitulos y actividades',
                'db_table': 'avanceObraGrafico2_esquemaCapitulosActividades',
                'permissions': (('can_see_esquemacapitulosactividadesgrafico', 'can see esquemacapitulosactividadesgrafico'),),
            },
        ),
        migrations.CreateModel(
            name='CReglasEstadoG',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('orden', models.IntegerField()),
                ('operador', models.IntegerField()),
                ('limite', models.FloatField()),
                ('esquema', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='regla_esquema_grafico', to='avanceObraGrafico2.BEsquemaCapitulosG')),
            ],
            options={
                'verbose_name': 'estructura de estado del cronograma',
                'db_table': 'avanceObraGrafico2_reglaEstado',
                'permissions': (('can_see_reglaEstadografico', 'can see reglaestadografico'),),
            },
        ),
        migrations.CreateModel(
            name='Cronograma',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('programacionCerrada', models.BooleanField(default=False)),
                ('esquema', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cronograma_esquema_grafico', to='avanceObraGrafico2.BEsquemaCapitulosG')),
                ('estado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cronograma_reglaEstado_grafico', to='avanceObraGrafico2.CReglasEstadoG')),
                ('periodicidad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cronograma_perioridicidad_grafico', to='avanceObraGrafico2.APeriodicidadG')),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cronograma_proyecto_grafico', to='proyecto.Proyecto')),
            ],
            options={
                'verbose_name': 'Cronograma',
                'db_table': 'avanceObraGrafico2_cronograma',
                'permissions': (('can_see_cronograma', 'can see cronograma'),),
            },
        ),
        migrations.CreateModel(
            name='EPresupuesto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('cerrar_presupuesto', models.BooleanField(default=False)),
                ('sin_poste', models.BooleanField(default=False)),
                ('cronograma', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='presupuesto_cronograma_grafico', to='avanceObraGrafico2.Cronograma')),
            ],
            options={
                'verbose_name': 'Encabezado de presupuesto',
                'db_table': 'avanceObraGrafico2_presupuesto',
                'permissions': (('can_see_presupuesto', 'can see presupuesto'),),
            },
        ),
        migrations.CreateModel(
            name='EReformado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_registro', models.DateField(blank=True, null=True)),
                ('usuario_registro', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reporte_reforamado_usuario', to='usuario.Usuario')),
            ],
            options={
                'verbose_name': 'Encabezado de Reformado',
                'db_table': 'avanceObraGrafico2_reformado',
                'permissions': (('can_see_presupuesto', 'can see presupuesto'),),
            },
        ),
        migrations.CreateModel(
            name='FDetallePresupuesto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigoUC', models.CharField(blank=True, max_length=20, null=True)),
                ('descripcionUC', models.CharField(blank=True, max_length=255, null=True)),
                ('valorManoObra', models.DecimalField(blank=True, decimal_places=4, max_digits=30, null=True)),
                ('valorMaterial', models.DecimalField(blank=True, decimal_places=4, max_digits=30, null=True)),
                ('valorGlobal', models.DecimalField(blank=True, decimal_places=4, max_digits=30, null=True)),
                ('cantidad', models.DecimalField(blank=True, decimal_places=4, max_digits=30, null=True)),
                ('porcentaje', models.DecimalField(blank=True, decimal_places=2, max_digits=30, null=True)),
                ('actividad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='detallePresupuesto_esquemacpitulosactividades_grafico', to='avanceObraGrafico2.CEsquemaCapitulosActividadesG')),
                ('catalogoUnidadConstructiva', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='detallePresupuesto_catalogoUnidadConstructiva', to='avanceObraGrafico2.CatalogoUnidadConstructiva')),
                ('presupuesto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='detallePresupuesto_presupuesto_grafico', to='avanceObraGrafico2.EPresupuesto')),
            ],
            options={
                'verbose_name': 'detalle de presupuesto',
                'db_table': 'avanceObraGrafico2_detallePresupuesto',
                'permissions': (('can_see_detallepresupuesto', 'can see detallepresupuesto'),),
            },
        ),
        migrations.CreateModel(
            name='GCapa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('color', colorfield.fields.ColorField(default='#000000', max_length=18)),
            ],
            options={
                'verbose_name': 'Capa',
                'db_table': 'avanceObraGrafico2_capa',
                'unique_together': {('nombre',)},
            },
        ),
        migrations.CreateModel(
            name='HNodo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('longitud', models.CharField(max_length=50, null=True)),
                ('latitud', models.CharField(max_length=50, null=True)),
                ('noProgramado', models.BooleanField(default=False)),
                ('eliminado', models.BooleanField(default=False)),
                ('porcentajeAcumulado', models.FloatField(blank=True, null=True)),
                ('capa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='nodo_capa_grafico', to='avanceObraGrafico2.GCapa')),
                ('presupuesto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='nodo_presupuesto_grafico', to='avanceObraGrafico2.EPresupuesto')),
            ],
            options={
                'verbose_name': 'Nodo',
                'db_table': 'avanceObraGrafico2_nodo',
                'permissions': (('can_see_nodo', 'can see nodo'),),
            },
        ),
        migrations.CreateModel(
            name='JReporteTrabajo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaTrabajo', models.DateField(blank=True, null=True)),
                ('valor_ganando_acumulado', models.FloatField(null=True)),
                ('avance_obra_acumulado', models.DecimalField(blank=True, decimal_places=2, max_digits=30, null=True)),
                ('sinAvance', models.BooleanField(default=False)),
                ('motivoSinAvance', models.CharField(blank=True, max_length=255, null=True)),
                ('fecharevision', models.DateField(blank=True, null=True)),
                ('soporteAprobacion', models.FileField(blank=True, null=True, upload_to='avanceObraGrafico_archivo')),
                ('reporteCerrado', models.BooleanField(default=False)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reporte_empresa', to='empresa.Empresa')),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reportetrabajo_estado', to='estado.Estado')),
                ('presupuesto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reportetrabajo_presupuesto_grafico', to='avanceObraGrafico2.EPresupuesto')),
                ('usuario_aprueba', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reportetrabajo_usuarioaprueba_grafico', to='usuario.Usuario')),
                ('usuario_registro', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reportetrabajo_usuario_grafico', to='usuario.Usuario')),
            ],
            options={
                'verbose_name': 'Reporte de Trabajo',
                'db_table': 'avanceObraGrafico2_reportetrabajo',
                'permissions': (('can_see_jreportetrabajo', 'can see jreportetrabajo'),),
            },
        ),
        migrations.CreateModel(
            name='KDetalleReporteTrabajo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidadEjecutada', models.DecimalField(decimal_places=2, max_digits=30)),
                ('liquidada', models.BooleanField(default=False)),
                ('detallepresupuesto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='detallereportetrabajo_detallepresupuesto_grafico', to='avanceObraGrafico2.FDetallePresupuesto')),
                ('nodo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='detallereportetrabajo_nodo_grafico', to='avanceObraGrafico2.HNodo')),
                ('reporte_trabajo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='detallereportetrabajo_reportetrabajo_grafico', to='avanceObraGrafico2.JReporteTrabajo')),
            ],
            options={
                'verbose_name': 'Detalle de Reporte de Trabajo',
                'db_table': 'avanceObraGrafico2_detallereportetrabajo',
                'permissions': (('can_see_kdetallereportetrabajo', 'can see kdetallereportetrabajo'),),
            },
        ),
        migrations.CreateModel(
            name='LCambio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(blank=True, max_length=255, null=True)),
                ('motivo', models.CharField(blank=True, max_length=255, null=True)),
                ('fecha_creacion', models.DateField(auto_now_add=True)),
                ('empresaFinanciera', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cambio_empresaFinanciera_grafico', to='empresa.Empresa')),
                ('empresaSolicitante', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cambio_empresaSolicitante_grafico', to='empresa.Empresa')),
                ('empresaTecnica', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cambio_empresaoTecnica_grafico', to='empresa.Empresa')),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cambio_estado_grafico', to='estado.Estado')),
                ('presupuesto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cambio_presupuesto_grafico', to='avanceObraGrafico2.EPresupuesto')),
            ],
            options={
                'verbose_name': 'Cambio',
                'db_table': 'avanceObraGrafico2_cambio',
                'permissions': (('can_see_cambio', 'can see cambio'), ('can_see_aprobacioncambio', 'can see aprobacioncambio'), ('can_see_autorizacioncambio', 'can see autorizacioncambio')),
            },
        ),
        migrations.CreateModel(
            name='TipoUnidadConstructiva',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('activa', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Tipo de unidad constructiva',
                'db_table': 'avanceObraGrafico2_tipounidadconstructiva',
            },
        ),
        migrations.CreateModel(
            name='UnidadConstructiva',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20)),
                ('descripcion', models.CharField(max_length=200)),
                ('catalogo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='unidadConstructiva_catalogo', to='avanceObraGrafico2.CatalogoUnidadConstructiva')),
                ('tipoUnidadConstructiva', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='unidadConstructiva_tipo', to='avanceObraGrafico2.TipoUnidadConstructiva')),
            ],
            options={
                'verbose_name': 'Unidad constructiva',
                'db_table': 'avancedeObraGrafico2_unidadconstructiva',
            },
        ),
        migrations.CreateModel(
            name='MLiquidacionUUCC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.IntegerField(choices=[(1, 'Abierta'), (2, 'Cerrada'), (3, 'Anulada')], default=1)),
                ('fecha', models.DateField(auto_now_add=True)),
                ('motivo_anulacion', models.CharField(blank=True, max_length=150, null=True)),
                ('detallereportetrabajo', models.ManyToManyField(related_name='fk_liquidacion_detallereportetrabajo', to='avanceObraGrafico2.KDetalleReporteTrabajo')),
                ('presupuesto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='liquidacionuucc_presupuesto', to='avanceObraGrafico2.EPresupuesto')),
            ],
            options={
                'db_table': 'avanceObraGrafico2_liquidacionuucc',
                'ordering': ['id'],
                'permissions': (('can_see_mliquidacionuucc', 'can see mliquidacionuucc'),),
            },
        ),
        migrations.CreateModel(
            name='MComentarioRechazo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivoRechazo', models.CharField(blank=True, max_length=255, null=True)),
                ('fecha_hora', models.DateTimeField(auto_now_add=True)),
                ('reporte_trabajo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='comentariorechazo_reportetrabajo_grafico', to='avanceObraGrafico2.JReporteTrabajo')),
            ],
            options={
                'verbose_name': 'Comentario de Rechazo',
                'db_table': 'avanceObraGrafico2_comentariorechazo',
                'permissions': (('can_see_comentariorechazo', 'can see comentariorechazo'),),
            },
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20)),
                ('descripcion', models.CharField(max_length=200)),
                ('valorUnitario', models.DecimalField(blank=True, decimal_places=2, max_digits=30, null=True)),
                ('unidadMedida', models.CharField(default='Und', max_length=10)),
                ('catalogo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Material_catalogo', to='avanceObraGrafico2.CatalogoUnidadConstructiva')),
            ],
            options={
                'verbose_name': 'Material',
                'db_table': 'avanceObraGrafico2_material',
            },
        ),
        migrations.CreateModel(
            name='ManoDeObra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20)),
                ('descripcion', models.CharField(max_length=200)),
                ('valorHora', models.DecimalField(decimal_places=2, max_digits=30)),
                ('catalogo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ManoDeObra_catalogo', to='avanceObraGrafico2.CatalogoUnidadConstructiva')),
            ],
            options={
                'verbose_name': 'Mano de obra',
                'db_table': 'avanceObraGrafico2_manodeobra',
            },
        ),
        migrations.CreateModel(
            name='LSoporteCambio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_soporte', models.CharField(max_length=255)),
                ('soporte', models.FileField(blank=True, null=True, upload_to='avanceObraGrafico_cambio_archivo')),
                ('cambio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='soportecambio_cambio_grafico', to='avanceObraGrafico2.LCambio')),
            ],
            options={
                'verbose_name': 'Soporte del Cambio',
                'db_table': 'avanceObraGrafico2_soportecambio',
                'permissions': (('can_see_soportecambio', 'can see soportecambio'),),
            },
        ),
        migrations.CreateModel(
            name='LHistorialCambio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now_add=True)),
                ('motivoEstado', models.CharField(blank=True, max_length=255, null=True)),
                ('cambio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='historialcambio_cambio_grafico', to='avanceObraGrafico2.LCambio')),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='historialcambio_estado_grafico', to='estado.Estado')),
                ('usuario_registro', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='historialcambio_usuario_grafico', to='usuario.Usuario')),
            ],
            options={
                'verbose_name': 'Historial del Cambio',
                'db_table': 'avanceObraGrafico2_historialcambio',
                'permissions': (('can_see_historialcambio', 'can see historialcambio'),),
            },
        ),
        migrations.CreateModel(
            name='LDetalleCambio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigoUC', models.CharField(blank=True, max_length=20, null=True)),
                ('descripcionUC', models.CharField(blank=True, max_length=255, null=True)),
                ('valorManoObra', models.DecimalField(blank=True, decimal_places=2, max_digits=30, null=True)),
                ('valorMaterial', models.DecimalField(blank=True, decimal_places=2, max_digits=30, null=True)),
                ('valorGlobal', models.DecimalField(blank=True, decimal_places=2, max_digits=30, null=True)),
                ('operacion', models.IntegerField()),
                ('cantidadPropuesta', models.DecimalField(blank=True, decimal_places=2, max_digits=30, null=True)),
                ('cambio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='detallecambio_cambio_grafico', to='avanceObraGrafico2.LCambio')),
                ('detallepresupuesto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='detallecambio_detallepresupuesto_grafico', to='avanceObraGrafico2.FDetallePresupuesto')),
                ('nodo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='detallecambio_nodo_grafico', to='avanceObraGrafico2.HNodo')),
            ],
            options={
                'verbose_name': 'Detalle de Cambio',
                'db_table': 'avanceObraGrafico2_detallecambio',
                'permissions': (('can_see_detallecambio', 'can see detallecambio'),),
            },
        ),
        migrations.CreateModel(
            name='JCantidadesNodo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=30)),
                ('detallepresupuesto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cantidadesnodo_detallepresupuesto_grafico', to='avanceObraGrafico2.FDetallePresupuesto')),
                ('nodo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cantidadesnodo_nodo_grafico', to='avanceObraGrafico2.HNodo')),
            ],
            options={
                'verbose_name': 'cantidades por nodo',
                'db_table': 'avanceObraGrafico2_cantidadesnodo',
                'permissions': (('can_see_cantidadesnodo', 'can see cantidadesnodo'),),
            },
        ),
        migrations.CreateModel(
            name='IEnlace',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='enlace_capa_grafico', to='avanceObraGrafico2.GCapa')),
                ('detallepresupuesto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='enlance_detallepresupuesto_grafico', to='avanceObraGrafico2.FDetallePresupuesto')),
                ('nodoDestino', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='nododestino_nodo_grafico', to='avanceObraGrafico2.HNodo')),
                ('nodoOrigen', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='nodoorigen_nodo_grafico', to='avanceObraGrafico2.HNodo')),
            ],
            options={
                'verbose_name': 'enlace entre nodos',
                'db_table': 'avanceObraGrafico2_enlace',
                'permissions': (('can_see_enlace', 'can see enlace'),),
            },
        ),
        migrations.CreateModel(
            name='FotoNodo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('ruta', models.FileField(blank=True, null=True, upload_to='administrador_fotos/fotos_proyecto', verbose_name='Ruta')),
                ('comentario', models.TextField(blank=True, null=True)),
                ('nodo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fotoNodo_nodo', to='avanceObraGrafico2.HNodo')),
            ],
            options={
                'verbose_name': 'Fotos por nodo',
                'db_table': 'avanceObraGrafico2_fotonodo',
            },
        ),
        migrations.CreateModel(
            name='EReformadoDetalle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_uucc', models.TextField(blank=True, null=True)),
                ('descripcion_uucc', models.TextField(blank=True, null=True)),
                ('cantidad_anterior', models.FloatField(blank=True, null=True)),
                ('cantidad_final', models.FloatField(blank=True, null=True)),
                ('diferencia', models.FloatField(blank=True, null=True)),
                ('apoyo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reforma_nodo', to='avanceObraGrafico2.HNodo')),
                ('reformado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reporte_reforamado_fk', to='avanceObraGrafico2.EReformado')),
            ],
            options={
                'verbose_name': 'Encabezado de Reformado Detalle',
                'db_table': 'avanceObraGrafico2_reformado_detalle',
                'permissions': (('can_see_presupuesto', 'can see presupuesto'),),
            },
        ),
        migrations.CreateModel(
            name='DiagramaGrahm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaInicio', models.DateField(blank=True, null=True)),
                ('fechaFinal', models.DateField(blank=True, null=True)),
                ('actividad_inicial', models.BooleanField(default=False)),
                ('actividad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='diagramagrahm_actividad_grafico', to='avanceObraGrafico2.CEsquemaCapitulosActividadesG')),
                ('cronograma', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='diagramagrahm_cronograma_grafico', to='avanceObraGrafico2.Cronograma')),
            ],
            options={
                'verbose_name': 'Diagrama Grahm',
                'db_table': 'avanceObraGrafico2_diagrama',
                'permissions': (('can_see_diagramaGrahm', 'can see diagramaGrahm'),),
            },
        ),
        migrations.CreateModel(
            name='DesgloceMaterial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=4, max_digits=30)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='desgloceMaterial_material', to='avanceObraGrafico2.Material')),
                ('unidadConstructiva', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='desgloceMaterial_unidadConstructiva', to='avanceObraGrafico2.UnidadConstructiva')),
            ],
            options={
                'verbose_name': 'Desgloce de material',
                'db_table': 'avanceObraGrafico2_desglocematerial',
            },
        ),
        migrations.CreateModel(
            name='DesgloceManoDeObra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rendimiento', models.DecimalField(decimal_places=4, max_digits=30)),
                ('manoDeObra', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='desgloceManoDeObra_manoDeObra', to='avanceObraGrafico2.ManoDeObra')),
                ('unidadConstructiva', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='desgloceManoDeObra_unidadConstructiva', to='avanceObraGrafico2.UnidadConstructiva')),
            ],
            options={
                'verbose_name': 'Desgloce de mano de obra',
                'db_table': 'avanceObraGrafico2_desglocemanodeobra',
            },
        ),
    ]
