# Generated by Django 2.2.10 on 2023-01-20 22:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tipo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('app', models.CharField(max_length=250)),
                ('color', models.CharField(blank=True, max_length=250)),
                ('codigo', models.IntegerField(blank=True, null=True)),
                ('icono', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'unique_together': {('app', 'codigo')},
            },
        ),
        migrations.CreateModel(
            name='Tipos_posibles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actual', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='f_Tipo_tipo', to='tipo.Tipo')),
                ('siguiente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='f_Tipo_tipo_2', to='tipo.Tipo')),
            ],
        ),
    ]
