# Generated by Django 2.2.10 on 2023-01-30 15:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AIndicador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('unidadMedida', models.CharField(max_length=10)),
                ('objetivoAnual', models.CharField(max_length=10)),
            ],
            options={
                'verbose_name': 'Indicador',
                'db_table': 'Calidad_indicador',
                'permissions': (('can_see_aindicador', 'can see aindicador'),),
            },
        ),
        migrations.CreateModel(
            name='Periodicidad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dias', models.IntegerField()),
                ('descripcion', models.CharField(max_length=150)),
            ],
            options={
                'db_table': 'Calidad_periodicidad',
            },
        ),
        migrations.CreateModel(
            name='BSeguimientoIndicador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inicioPeriodo', models.DateField()),
                ('finPeriodo', models.DateField()),
                ('valor', models.FloatField()),
                ('indicador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='seguimientoIndicadorCalidad', to='indicadorCalidad.AIndicador')),
            ],
            options={
                'verbose_name': 'SeguimientoIndicador',
                'db_table': 'Calidad_seguimientoIndicador',
                'permissions': (('can_see_bseguimientoindicador', 'can see bseguimientoindicador'),),
            },
        ),
        migrations.AddField(
            model_name='aindicador',
            name='periodicidad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='IndicadorPeriodicidad', to='indicadorCalidad.Periodicidad'),
        ),
    ]
