# Generated by Django 2.2.10 on 2023-01-20 22:33

from django.db import migrations, models
import django.db.models.deletion
import coasmedas.functions


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contrato', '0001_initial'),
        ('tipo', '0001_initial'),
        ('empresa', '0001_initial'),
        ('estado', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinancieroCuenta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('numero', models.CharField(blank=True, max_length=50, null=True)),
                ('valor', models.FloatField()),
                ('fiduciaria', models.CharField(blank=True, max_length=100, null=True)),
                ('codigo_fidecomiso', models.CharField(blank=True, max_length=10, null=True)),
                ('codigo_fidecomiso_a', models.CharField(blank=True, max_length=10, null=True)),
                ('nombre_fidecomiso', models.CharField(blank=True, max_length=250, null=True)),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='financiero_cuenta_contrato', to='contrato.Contrato')),
                ('empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fk_Empresa_empresa', to='empresa.Empresa')),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='estado.Estado')),
                ('tipo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='financiero_cuenta_tipo', to='tipo.Tipo')),
            ],
            options={
                'db_table': 'financiero_cuenta',
                'permissions': (('can_see_financierocuenta', 'can_see_financierocuenta'), ('can_see_financieroEstado', 'can_see_financieroEstado'), ('can_see_financieroMovimiento', 'can_see_financieroMovimiento')),
            },
        ),
        migrations.CreateModel(
            name='NExtracto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes', models.IntegerField(blank=True, null=True)),
                ('ano', models.IntegerField(blank=True, null=True)),
                ('soporte', models.FileField(blank=True, null=True, upload_to=coasmedas.functions.RandomFileName('financiero/extracto', 'extracto'))),
                ('cuenta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='financiero_cuenta_extracto', to='financiero.FinancieroCuenta')),
            ],
            options={
                'db_table': 'financiero_cuenta_extracto',
                'permissions': (('can_see_financieroextracto', 'can_see_financieroextracto'),),
            },
        ),
        migrations.CreateModel(
            name='FinancieroCuentaMovimiento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.FloatField()),
                ('descripcion', models.CharField(blank=True, max_length=100, null=True)),
                ('fecha', models.DateField(blank=True, null=True)),
                ('periodo_inicio', models.CharField(blank=True, max_length=50, null=True)),
                ('periodo_final', models.CharField(blank=True, max_length=50, null=True)),
                ('ano', models.IntegerField(blank=True, null=True)),
                ('bloquear', models.BooleanField(default=False)),
                ('cuenta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='financiero_cuenta_movimiento', to='financiero.FinancieroCuenta')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='financiero_cuenta_movimiento', to='tipo.Tipo')),
            ],
            options={
                'db_table': 'financiero_cuenta_movimiento',
                'permissions': (('can_see_financierocuentamovimiento', 'can_see_financierocuentamovimiento'),),
            },
        ),
    ]
