# Generated by Django 2.2.10 on 2023-01-30 15:34

from django.db import migrations, models
import django.db.models.deletion
import coasmedas.functions


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuario', '0001_initial'),
        ('estado', '0001_initial'),
        ('proyecto', '0001_initial'),
        ('tipo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Servidumbre_documento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60)),
            ],
            options={
                'db_table': 'servidumbre_documento',
            },
        ),
        migrations.CreateModel(
            name='Servidumbre_expediente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateField(auto_now_add=True)),
                ('estado', models.ForeignKey(default=159, on_delete=django.db.models.deletion.PROTECT, related_name='f_Servidumbre_documento_Estado', to='estado.Estado')),
                ('proyecto', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='f_proyecto_proyecto', to='proyecto.Proyecto')),
                ('usuario_creador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='f_Usuario_usuario', to='usuario.Usuario')),
            ],
            options={
                'db_table': 'servidumbre_expediente',
                'permissions': (('can_see_Expediente', 'can_see_Expediente'),),
                'unique_together': {('proyecto',)},
            },
        ),
        migrations.CreateModel(
            name='Servidumbre_grupo_documento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60)),
            ],
            options={
                'db_table': 'servidumbre_grupo_documento',
                'permissions': (('can_see_ExpedienteGrupoDocumento', 'can_see_ExpedienteGrupoDocumento'),),
                'unique_together': {('nombre',)},
            },
        ),
        migrations.CreateModel(
            name='Servidumbre_persona',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cedula', models.IntegerField(unique=True)),
                ('nombres', models.CharField(max_length=60)),
                ('apellidos', models.CharField(max_length=60)),
                ('celular', models.CharField(blank=True, max_length=60)),
                ('telefono', models.CharField(blank=True, max_length=60)),
            ],
            options={
                'db_table': 'servidumbre_persona',
            },
        ),
        migrations.CreateModel(
            name='Servidumbre_predio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_direccion', models.CharField(max_length=150, unique=True)),
                ('expediente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fk_Servidumbre_expediente', to='servidumbre.Servidumbre_expediente')),
                ('grupo_documento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fk_Servidumbre_grupo_documento', to='servidumbre.Servidumbre_grupo_documento')),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fk_Servidumbre_persona', to='servidumbre.Servidumbre_persona')),
                ('tipo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fk_Servidumbre_predio_Tipo', to='tipo.Tipo')),
            ],
            options={
                'db_table': 'servidumbre_predio',
                'unique_together': {('persona', 'nombre_direccion')},
            },
        ),
        migrations.CreateModel(
            name='Servidumbre_predio_documento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60)),
                ('archivo', models.FileField(null=True, upload_to=coasmedas.functions.RandomFileName('servidumbre', 'ser'))),
                ('documento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='f_Servidumbre_documento', to='servidumbre.Servidumbre_documento')),
                ('predio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='f_Servidumbre_predio', to='servidumbre.Servidumbre_predio')),
            ],
            options={
                'db_table': 'servidumbre_predio_documento',
            },
        ),
        migrations.AddField(
            model_name='servidumbre_documento',
            name='grupo_documento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='f_Servidumbre_grupo_documento', to='servidumbre.Servidumbre_grupo_documento'),
        ),
        migrations.CreateModel(
            name='Servidumbre_predio_georeferencia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orden', models.IntegerField(blank=True, null=True)),
                ('longitud', models.CharField(max_length=50)),
                ('latitud', models.CharField(max_length=50)),
                ('predio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='f_Servidumbre_georeferencia_predio', to='servidumbre.Servidumbre_predio')),
            ],
            options={
                'db_table': 'servidumbre_predio_georefencia',
                'permissions': (('can_see_predio_georefencia', 'can_see_predio_georefencia'),),
                'unique_together': {('predio', 'orden')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='servidumbre_documento',
            unique_together={('grupo_documento', 'nombre')},
        ),
    ]
