# Generated by Django 2.2.10 on 2023-01-20 22:34

from django.db import migrations, models
import django.db.models.deletion
import coasmedas.functions


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contrato', '0001_initial'),
        ('tipo', '0001_initial'),
        ('proyecto', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ACategoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(blank=True, max_length=500, null=True)),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='administrador_fotos_contrato', to='contrato.Contrato')),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='administradorFotosProyecto', to='proyecto.Proyecto')),
            ],
            options={
                'verbose_name': 'Categoria',
                'db_table': 'administrador_categoria',
                'permissions': (('can_see_AdministradorCategoria', 'can_see_AdministradorCategoria'), ('can_see_ActividadesContratista', 'can_see_ActividadesContratista'), ('can_see_Subcategoria', 'can_see_Subcategoria')),
            },
        ),
        migrations.CreateModel(
            name='BSubcategoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(blank=True, max_length=300, null=True)),
                ('contenido', models.TextField(blank=True, null=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='administrador_fotos_categoria', to='administrador_fotos.ACategoria')),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='administrador_fotos_proyecto', to='proyecto.Proyecto')),
            ],
            options={
                'verbose_name': 'Subcategoria',
                'db_table': 'administrador_subcategoria',
                'permissions': (('can_see_AdministradorSubcategoria', 'can_see_AdministradorSubcategoria'), ('can_see_FotoSubcategoria', 'can_see_FotoSubcategoria')),
            },
        ),
        migrations.CreateModel(
            name='DFotosSubcategoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ruta', models.FileField(blank=True, null=True, upload_to=coasmedas.functions.RandomFileName('administrador_fotos/subcategoria_fotos', 'plz'))),
                ('mes', models.IntegerField(blank=True, default=0, null=True)),
                ('ano', models.IntegerField(blank=True, default=0, null=True)),
                ('subcategoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='administrador_fotos_subcategoria', to='administrador_fotos.BSubcategoria')),
            ],
            options={
                'verbose_name': 'Fotos subcategoria',
                'db_table': 'administrador_fotos_subcategoria',
                'permissions': (('can_see_AdministradorFotosSubcategoria', 'can_see_AdministradorFotosSubcategoria'),),
            },
        ),
        migrations.CreateModel(
            name='CFotosProyecto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(blank=True, null=True)),
                ('ruta', models.FileField(blank=True, null=True, upload_to=coasmedas.functions.RandomFileName('administrador_fotos/fotos_proyecto'), verbose_name='Ruta')),
                ('comentarios', models.TextField(blank=True, null=True)),
                ('asociado_reporte', models.BooleanField(default=False)),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='administradorFotos_proyecto', to='proyecto.Proyecto')),
                ('tipo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='administrador_fotos_tipo', to='tipo.Tipo')),
            ],
            options={
                'verbose_name': 'Fotos proyectos',
                'db_table': 'administrador_fotos_proyecto',
                'permissions': (('can_see_AdministradorFotosProyecto', 'can_see_AdministradorFotosProyecto'), ('can_see_fotosProyecto', 'can_see_fotosProyecto')),
            },
        ),
    ]
