# Generated by Django 2.2.10 on 2023-01-30 15:31

import colorfield.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contrato', '0001_initial'),
        ('usuario', '0001_initial'),
        ('proyecto', '0001_initial'),
        ('empresa', '0001_initial'),
        ('tipo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BEsquemaCapitulosG',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('macrocontrato', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='esquema_contratog', to='contrato.Contrato')),
            ],
            options={
                'verbose_name': 'Esquemas',
                'db_table': 'avanceObraGrafico_esquemaCapitulos',
                'permissions': (('can_see_esquemacapitulosg', 'can see esquemacapitulosg'),),
            },
        ),
        migrations.CreateModel(
            name='CEsquemaCapitulosActividadesG',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('nivel', models.IntegerField()),
                ('padre', models.IntegerField()),
                ('peso', models.FloatField()),
                ('esquema', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='actividades_esquemag', to='avanceObraGrafico.BEsquemaCapitulosG')),
            ],
            options={
                'verbose_name': 'Capitulos y actividades',
                'db_table': 'avanceObraGrafico_esquemaCapitulosActividades',
                'permissions': (('can_see_esquemacapitulosactividadesg', 'can see esquemacapitulosactividadesg'),),
            },
        ),
        migrations.CreateModel(
            name='DReglasEstadoG',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('orden', models.IntegerField()),
                ('operador', models.IntegerField()),
                ('limite', models.FloatField()),
                ('esquema', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='regla_esquemag', to='avanceObraGrafico.BEsquemaCapitulosG')),
            ],
            options={
                'verbose_name': 'estructura de estado del cronograma',
                'db_table': 'avanceObraGrafico_reglaEstado',
                'permissions': (('can_see_reglaEstadog', 'can see reglaestadog'),),
            },
        ),
        migrations.CreateModel(
            name='EPresupuesto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('cerrar_presupuesto', models.BooleanField(default=False)),
                ('esquema', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='presupuesto_esquemaCapitulos', to='avanceObraGrafico.BEsquemaCapitulosG')),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='presupuesto_proyecto_avanceobragrafico', to='proyecto.Proyecto')),
            ],
            options={
                'verbose_name': 'Encabezado de presupuesto',
                'db_table': 'avanceObraGrafico_presupuesto',
                'permissions': (('can_see_presupuesto', 'can see presupuesto'),),
            },
        ),
        migrations.CreateModel(
            name='FDetallePresupuesto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigoUC', models.CharField(blank=True, max_length=20, null=True)),
                ('descripcionUC', models.CharField(blank=True, max_length=255, null=True)),
                ('valorManoObra', models.DecimalField(blank=True, decimal_places=2, max_digits=30, null=True)),
                ('valorMaterial', models.DecimalField(blank=True, decimal_places=2, max_digits=30, null=True)),
                ('valorGlobal', models.DecimalField(blank=True, decimal_places=2, max_digits=30, null=True)),
                ('cantidad', models.DecimalField(blank=True, decimal_places=2, max_digits=30, null=True)),
                ('porcentaje', models.DecimalField(blank=True, decimal_places=2, max_digits=30, null=True)),
                ('actividad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='detallePresupuesto_esquemacpitulosactividades', to='avanceObraGrafico.CEsquemaCapitulosActividadesG')),
                ('presupuesto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='detallePresupuesto_presupuesto', to='avanceObraGrafico.EPresupuesto')),
            ],
            options={
                'verbose_name': 'detalle de presupuesto',
                'db_table': 'avanceObraGrafico_detallePresupuesto',
                'permissions': (('can_see_detallepresupuesto', 'can see detallepresupuesto'),),
            },
        ),
        migrations.CreateModel(
            name='GCapa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('color', colorfield.fields.ColorField(default='#000000', max_length=18)),
            ],
            options={
                'verbose_name': 'Capa',
                'db_table': 'avanceObraGrafico_capa',
                'unique_together': {('nombre',)},
            },
        ),
        migrations.CreateModel(
            name='HNodo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('longitud', models.CharField(max_length=50, null=True)),
                ('latitud', models.CharField(max_length=50, null=True)),
                ('noProgramado', models.BooleanField(default=False)),
                ('eliminado', models.BooleanField(default=False)),
                ('capa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='capaDelNodo', to='avanceObraGrafico.GCapa')),
                ('presupuesto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='nodo_presupuesto', to='avanceObraGrafico.EPresupuesto')),
            ],
            options={
                'verbose_name': 'Nodo',
                'db_table': 'avanceObraGrafico_nodo',
                'permissions': (('can_see_nodo', 'can see nodo'),),
            },
        ),
        migrations.CreateModel(
            name='JCantidadesNodo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=30)),
                ('detallepresupuesto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cantidadesnodo_detallepresupuesto', to='avanceObraGrafico.FDetallePresupuesto')),
                ('nodo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cantidadesnodo_nodo', to='avanceObraGrafico.HNodo')),
            ],
            options={
                'verbose_name': 'cantidades por nodo',
                'db_table': 'avanceObraGrafico_cantidadesnodo',
                'permissions': (('can_see_cantidadesnodo', 'can see cantidadesnodo'),),
                'unique_together': {('detallepresupuesto', 'nodo')},
            },
        ),
        migrations.CreateModel(
            name='KCronograma',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('fechaInicio', models.DateField(null=True)),
                ('programacionCerrada', models.BooleanField(default=False)),
                ('estado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cronograma_reglaEstado', to='avanceObraGrafico.DReglasEstadoG')),
                ('presupuesto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cronograma_presupuesto', to='avanceObraGrafico.EPresupuesto')),
            ],
            options={
                'verbose_name': 'Cronograma',
                'db_table': 'avanceObraGrafico_cronograma',
                'permissions': (('can_see_cronograma', 'can see cronograma'),),
            },
        ),
        migrations.CreateModel(
            name='LProgramacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(blank=True, null=True)),
                ('tipo_linea', models.IntegerField()),
                ('cantidadesNodo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='programacion_cantidadesnodo', to='avanceObraGrafico.JCantidadesNodo')),
                ('cronograma', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='programacion_cronograma', to='avanceObraGrafico.KCronograma')),
            ],
            options={
                'verbose_name': 'Programacion de trabajos',
                'db_table': 'avanceObraGrafico_programacion',
                'permissions': (('can_see_programacion', 'can see programacion'),),
            },
        ),
        migrations.CreateModel(
            name='MEstadoCambio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Estados de un cambio',
                'db_table': 'avanceObraGrafico_estado',
                'permissions': (('can_see_estadoCambio', 'can see estadoCambio'),),
                'unique_together': {('nombre',)},
            },
        ),
        migrations.CreateModel(
            name='NCambio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('motivo', models.CharField(max_length=500)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('motivoRechazoTecnico', models.CharField(blank=True, max_length=255, null=True)),
                ('motivoRechazoFinanciero', models.CharField(blank=True, max_length=255, null=True)),
                ('motivoCancelacion', models.CharField(blank=True, max_length=255, null=True)),
                ('cronograma', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cambio_cronograma', to='avanceObraGrafico.KCronograma')),
                ('empresa_financiera', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cambio_empresa_financiera', to='empresa.Empresa')),
                ('empresa_tecnica', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cambio_empresa_tecnica', to='empresa.Empresa')),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cambio_estadocambio', to='avanceObraGrafico.MEstadoCambio')),
                ('nodos', models.ManyToManyField(blank=True, related_name='cambio_nodo', to='avanceObraGrafico.HNodo')),
                ('solicitante', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cambio_usuario_solicitante', to='usuario.Usuario')),
                ('tipo_accion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cambio_tipo_accion', to='tipo.Tipo')),
            ],
            options={
                'verbose_name': 'Encabezado del control de cambios',
                'db_table': 'avanceObraGrafico_cambio',
                'permissions': (('can_see_cambios', 'can see cambios'),),
            },
        ),
        migrations.CreateModel(
            name='RPorcentajeApoyo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('porcentaje', models.FloatField()),
                ('apoyo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='porcentaje_apoyo', to='avanceObraGrafico.HNodo')),
                ('cronograma', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='porcentaje_apoyo_cronograma', to='avanceObraGrafico.KCronograma')),
            ],
            options={
                'verbose_name': 'Porcentaje de Apoyo',
                'db_table': 'avanceObraGrafico_porcentaje_apoyo',
                'permissions': (('can_see_porcentaje_apoyo', 'can see porcentaje_apoyo'),),
            },
        ),
        migrations.CreateModel(
            name='RDiagramaGrahm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaInicio', models.DateField(blank=True, null=True)),
                ('fechaFinal', models.DateField(blank=True, null=True)),
                ('actividad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='diagramagrahm_actividad', to='avanceObraGrafico.CEsquemaCapitulosActividadesG')),
                ('presupuesto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='diagramagrahm_presupuesto', to='avanceObraGrafico.EPresupuesto')),
            ],
            options={
                'verbose_name': 'Diagrama Grahm',
                'db_table': 'avanceObraGrafico_diagrama',
                'permissions': (('can_see_diagramaGrahm', 'can see diagramaGrahm'),),
            },
        ),
        migrations.CreateModel(
            name='PDetalleCambio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=3, max_digits=30)),
                ('fechaProgramada', models.DateField(blank=True, null=True)),
                ('cambio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='detalleCambio_cambio', to='avanceObraGrafico.NCambio')),
                ('detallePresupuesto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='detalleCambio_detallePresupuesto', to='avanceObraGrafico.FDetallePresupuesto')),
                ('nodo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='detalleCambio_nodo', to='avanceObraGrafico.HNodo')),
            ],
            options={
                'verbose_name': 'Detalle del cambio',
                'db_table': 'avanceObraGrafico_detalleCambio',
                'permissions': (('can_see_detalleCambio', 'can see detalleCambio'),),
            },
        ),
        migrations.CreateModel(
            name='LPorcentajePresupuesto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(null=True)),
                ('valor_ganando', models.FloatField()),
                ('cronograma', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='porcentaje_presupuesto_cronograma', to='avanceObraGrafico.KCronograma')),
                ('detallepresupuesto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='porcentaje_presupuesto_detallepresupuesto', to='avanceObraGrafico.FDetallePresupuesto')),
            ],
            options={
                'verbose_name': 'Porcentaje de saldo de trabajos',
                'db_table': 'avanceObraGrafico_porcentaje_presupuesto',
                'permissions': (('can_see_porcentaje_ganando', 'can see porcentaje_ganando'),),
            },
        ),
        migrations.CreateModel(
            name='LPorcentaje',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(null=True)),
                ('porcentaje', models.FloatField()),
                ('tipo_linea', models.IntegerField()),
                ('cronograma', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='porcentaje_cronograma', to='avanceObraGrafico.KCronograma')),
                ('detallepresupuesto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='porcentaje_detallepresupuesto', to='avanceObraGrafico.FDetallePresupuesto')),
            ],
            options={
                'verbose_name': 'Porcentaje de trabajos',
                'db_table': 'avanceObraGrafico_porcentaje',
                'permissions': (('can_see_porcentaje', 'can see porcentaje'),),
            },
        ),
        migrations.CreateModel(
            name='IEnlace',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='capaDelEnlace', to='avanceObraGrafico.GCapa')),
                ('detallepresupuesto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='enlance_detallepresupuesto', to='avanceObraGrafico.FDetallePresupuesto')),
                ('nodoDestino', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='nodoDestinoRefenciado', to='avanceObraGrafico.HNodo')),
                ('nodoOrigen', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='nodoOrigenRefenciado', to='avanceObraGrafico.HNodo')),
            ],
            options={
                'verbose_name': 'enlace entre nodos',
                'db_table': 'avanceObraGrafico_enlace',
                'permissions': (('can_see_enlace', 'can see enlace'),),
            },
        ),
        migrations.CreateModel(
            name='APeriodicidadG',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('numero_dias', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Periodicidad',
                'db_table': 'avanceObraGrafico_periodicidad',
                'permissions': (('can_see_periodicidadg', 'can see periodicidadg'),),
                'unique_together': {('nombre',)},
            },
        ),
        migrations.CreateModel(
            name='QEjecucionProgramada',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidadEjecutada', models.DecimalField(decimal_places=3, max_digits=30)),
                ('fecha', models.DateField(blank=True, null=True)),
                ('observacion', models.CharField(blank=True, max_length=255, null=True)),
                ('programacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ejecucionProgramada_programacion', to='avanceObraGrafico.LProgramacion')),
            ],
            options={
                'verbose_name': 'Ejecucion programada',
                'db_table': 'avanceObraGrafico_ejecucionProgramada',
                'permissions': (('can_see_ejecucionProgramada', 'can see ejecucionProgramada'),),
                'unique_together': {('programacion', 'cantidadEjecutada', 'fecha')},
            },
        ),
    ]
