# Generated by Django 2.2.10 on 2023-01-20 22:36

from django.db import migrations, models
import django.db.models.deletion
import sinin4.functions
import smart_selects.db_fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuario', '0001_initial'),
        ('parametrizacion', '0001_initial'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('empresa', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AProceso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('activo', models.BooleanField(default=True)),
                ('apuntador', models.CharField(choices=[('0', '[Seleccione...]'), ('1', 'Proyecto'), ('2', 'Contrato')], default=0, max_length=1)),
                ('campoEnlace', models.CharField(max_length=50, verbose_name='Campo enlace')),
                ('campoEnlaceTablaForanea', models.CharField(blank=True, max_length=50, null=True, verbose_name='Campo Tabla foranea de la referencia')),
                ('etiqueta', models.CharField(blank=True, max_length=50, null=True, verbose_name='Origen Etiqueta en implementacion')),
                ('pasoAPaso', models.BooleanField(default=False, verbose_name='Indica si el seguimiento se hace paso a paso (defina responsables de items)')),
                ('empresas', models.ManyToManyField(related_name='fk_empresasQueAccedenAlProceso', to='empresa.Empresa', verbose_name='Empresas que acceden al proceso')),
                ('tablaForanea', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fk_tablaForaneaRefenciaProceso', to='contenttypes.ContentType', verbose_name='Tabla foranea de la referencia')),
                ('tablaReferencia', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fk_tablaReferenciaProceso', to='contenttypes.ContentType', verbose_name='Tabla referenciada')),
            ],
            options={
                'verbose_name': 'Proceso',
                'db_table': 'Proceso_proceso',
                'permissions': (('can_see_proceso', 'can see proceso'),),
            },
        ),
        migrations.CreateModel(
            name='BItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orden', models.IntegerField(default=1)),
                ('descripcion', models.TextField(max_length=150)),
                ('tipoDato', models.CharField(choices=[('0', '[Seleccione...]'), ('1', 'Numerico'), ('2', 'Texto'), ('3', 'Si/No'), ('4', 'Fecha')], default=0, max_length=1, verbose_name='Tipo de dato')),
                ('notificacionCumplimiento', models.CharField(choices=[('1', 'A nadie'), ('2', 'A todos los responsables del proyecto/contrato'), ('3', 'Seleccionar a quien notificar')], default=1, max_length=1, verbose_name='Accion acerca de notificacion de cumplimiento')),
                ('tieneVencimiento', models.BooleanField(default=False)),
                ('tieneObservacion', models.BooleanField(default=False)),
                ('tieneSoporte', models.BooleanField(default=False)),
                ('soporteObligatorio', models.BooleanField(default=False)),
                ('activo', models.BooleanField(default=True)),
                ('afectarImplementacionesAnteriores', models.BooleanField(default=False, verbose_name='Defina como Si, en caso que desee afectar implementaciones realizadas')),
                ('contratistaResponsable', models.BooleanField(default=False, verbose_name='indica si el eventual contratista es el responsable de este item')),
                ('proceso', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='procesoDelItem', to='proceso.AProceso')),
                ('responsable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='responsableTitularItem', to='usuario.Usuario')),
            ],
            options={
                'verbose_name': 'Item',
                'db_table': 'Proceso_item',
            },
        ),
        migrations.CreateModel(
            name='FProcesoRelacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idApuntador', models.IntegerField(verbose_name='id del proyecto/contrato sobre el proceso')),
                ('idTablaReferencia', models.IntegerField()),
                ('proceso', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fk_procesoRelacion', to='proceso.AProceso')),
            ],
            options={
                'verbose_name': 'ProcesoRelacion',
                'db_table': 'Proceso_procesoRelacion',
                'unique_together': {('proceso', 'idApuntador', 'idTablaReferencia')},
            },
        ),
        migrations.CreateModel(
            name='GProcesoRelacionDato',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaVencimiento', models.DateField(blank=True, null=True, verbose_name='Fecha de vencimiento de cumplimiento del item')),
                ('observacion', models.TextField(blank=True, max_length=150, null=True)),
                ('valor', models.CharField(default='Vacio', max_length=50)),
                ('estado', models.CharField(choices=[('0', 'Por cumplir'), ('1', 'Cumplido'), ('2', 'Por vencer'), ('3', 'Vencido')], default=0, max_length=1)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fk_itemProcesoRelacionDatos', to='proceso.BItem')),
                ('procesoRelacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fk_DatosDelProcesoImplementado', to='proceso.FProcesoRelacion')),
            ],
            options={
                'verbose_name': 'ProcesoRelacionDatos',
                'db_table': 'Proceso_procesoRelacionDato',
                'unique_together': {('procesoRelacion', 'item')},
            },
        ),
        migrations.CreateModel(
            name='INotificacionVencimiento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('responsableTitular', models.BooleanField(default=False)),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fk_funcionarioANotificar', to='parametrizacion.Funcionario')),
                ('procesoRelacionDato', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fk_notificacionVencimientoProcesoRelacionDato', to='proceso.GProcesoRelacionDato')),
            ],
            options={
                'verbose_name': 'Notificacion de vencimiento',
                'db_table': 'Proceso_notificacionVencimiento',
            },
        ),
        migrations.CreateModel(
            name='HSoporteProcesoRelacionDato',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('documento', models.FileField(null=True, upload_to=sinin4.functions.RandomFileName('procesos/soportes', 'pso'))),
                ('procesoRelacionDato', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fk_soporteProcesoRelacionDato', to='proceso.GProcesoRelacionDato')),
            ],
            options={
                'verbose_name': 'Soportes del procesoRelacionDato',
                'db_table': 'Proceso_soporteProcesoRelacionDato',
            },
        ),
        migrations.CreateModel(
            name='ECampoInforme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreCampoApuntador', models.CharField(max_length=50)),
                ('campoTablaForanea', models.CharField(blank=True, max_length=50, null=True)),
                ('proceso', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fk_procesoConfInforme', to='proceso.AProceso')),
                ('tablaForanea', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fk_tablaForaneaRefencia', to='contenttypes.ContentType')),
            ],
            options={
                'verbose_name': 'CampoInforme',
                'db_table': 'Proceso_CampoInforme',
            },
        ),
        migrations.CreateModel(
            name='JSeguidorProcesoRelacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('procesoRelacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fk_seguidor_procesoRelacion', to='proceso.FProcesoRelacion')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fk_seguidor_usuario', to='usuario.Usuario')),
            ],
            options={
                'verbose_name': 'Seguidor de procesoRelacion',
                'db_table': 'Proceso_SeguidorProcesoRelacion',
                'unique_together': {('procesoRelacion', 'usuario')},
            },
        ),
        migrations.CreateModel(
            name='DVinculo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itemVinculado', smart_selects.db_fields.ChainedForeignKey(chained_field='procesoOrigen', chained_model_field='proceso', on_delete=django.db.models.deletion.PROTECT, related_name='fk_itemVinculadoEntreProcesos', to='proceso.BItem', verbose_name='item vinculado')),
                ('procesoDestino', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fk_vinculoProcesoDestino', to='proceso.AProceso', verbose_name='Proceso destino del vinculo')),
                ('procesoOrigen', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fk_vinculoProcesoOrigen', to='proceso.AProceso', verbose_name='Proceso origen del vinculo')),
            ],
            options={
                'verbose_name': 'items vinculados entre procesos',
                'db_table': 'Proceso_vinculo',
                'unique_together': {('procesoOrigen', 'procesoDestino', 'itemVinculado')},
            },
        ),
        migrations.CreateModel(
            name='CPermisoEmpresaItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lectura', models.BooleanField(default=True)),
                ('escritura', models.BooleanField(default=False)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fk_empresaConPermisoAlItem', to='empresa.Empresa')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fk_itemConPermisoAlaEmpresa', to='proceso.BItem')),
            ],
            options={
                'verbose_name': 'Permisos de empresas sobre items',
                'db_table': 'Proceso_permisoEmpresaItem',
                'unique_together': {('empresa', 'item')},
            },
        ),
    ]
