# Generated by Django 2.2.10 on 2023-01-20 22:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('proyecto', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ubicacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=1255)),
                ('longitud', models.CharField(max_length=70)),
                ('latitud', models.CharField(max_length=70)),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='proyecto.Proyecto')),
            ],
            options={
                'permissions': (('puede_ver', 'puede ver'),),
                'abstract': False,
            },
        ),
    ]
