# Generated by Django 2.2.10 on 2023-01-20 22:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contrato', '0001_initial'),
        ('usuario', '0001_initial'),
        ('proyecto', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AEsquemaCapitulos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('macrocontrato', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='esquema_contrato', to='contrato.Contrato')),
            ],
            options={
                'db_table': 'avance_de_obra_esquema_capitulos',
                'permissions': (('can_see_esquemacapitulos', 'can see esquemacapitulos'),),
            },
        ),
        migrations.CreateModel(
            name='AEsquemaCapitulosActividades',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('nivel', models.IntegerField()),
                ('padre', models.IntegerField()),
                ('peso', models.FloatField()),
                ('esquema', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='actividades_esquema', to='avance_de_obra.AEsquemaCapitulos')),
            ],
            options={
                'db_table': 'avance_de_obra_esquema_capitulos_actividades',
                'permissions': (('can_see_esquemacapitulosactividades', 'can see esquemacapitulosactividades'),),
            },
        ),
        migrations.CreateModel(
            name='APeriodicidad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('numero_dias', models.IntegerField()),
            ],
            options={
                'db_table': 'avance_de_obra_periodicidad',
                'permissions': (('can_see_periodicidad', 'can see periodicidad'),),
            },
        ),
        migrations.CreateModel(
            name='AReglasEstado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orden', models.IntegerField()),
                ('operador', models.IntegerField()),
                ('limite', models.FloatField()),
                ('estado', models.TextField(blank=True, null=True)),
                ('esquema', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='regla_esquema', to='avance_de_obra.AEsquemaCapitulos')),
            ],
            options={
                'db_table': 'avance_de_obra_regla_estado',
                'permissions': (('can_see_reglaEstado', 'can see reglaEstado'),),
            },
        ),
        migrations.CreateModel(
            name='BCronograma',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('intervalos', models.IntegerField()),
                ('linea_base_terminada', models.BooleanField(default=False)),
                ('fecha_inicio_cronograma', models.DateField(null=True)),
                ('esquema', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cronograma_esquema', to='avance_de_obra.AEsquemaCapitulos')),
                ('estado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cronograma_regla', to='avance_de_obra.AReglasEstado')),
                ('periodicidad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cronograma_periodicidad', to='avance_de_obra.APeriodicidad')),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cronograma_proyecto', to='proyecto.Proyecto')),
            ],
            options={
                'db_table': 'avance_de_obra_cronograma',
                'permissions': (('can_see_bcronograma', 'can see bcronograma'),),
            },
        ),
        migrations.CreateModel(
            name='CIntervaloCronograma',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intervalo', models.IntegerField()),
                ('tipo_linea', models.IntegerField()),
                ('sinAvance', models.BooleanField(default=False)),
                ('comentario_sinAvance', models.TextField(blank=True, null=True)),
                ('fecha_corte', models.DateField(null=True)),
                ('cronograma', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='intervalo_cronograma', to='avance_de_obra.BCronograma')),
            ],
            options={
                'db_table': 'avance_de_obra_intervalo_cronograma',
            },
        ),
        migrations.CreateModel(
            name='DActividad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cronograma', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='actividad_cronograma', to='avance_de_obra.BCronograma')),
                ('esquema_actividades', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='actividad_esquemactividades', to='avance_de_obra.AEsquemaCapitulosActividades')),
            ],
            options={
                'db_table': 'avance_de_obra_actividad',
                'permissions': (('can_see_dactividad', 'can see dactividad'),),
            },
        ),
        migrations.CreateModel(
            name='Soporte',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('ruta', models.FileField(blank=True, null=True, upload_to='avanceObra/soporte')),
                ('intervalo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='soporte_intervalo', to='avance_de_obra.CIntervaloCronograma')),
            ],
            options={
                'db_table': 'avance_de_obra_soporte',
            },
        ),
        migrations.CreateModel(
            name='Porcentaje',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_linea', models.IntegerField()),
                ('porcentaje', models.FloatField()),
                ('intervalo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='porcentaje_intervalo', to='avance_de_obra.CIntervaloCronograma')),
            ],
            options={
                'db_table': 'avance_de_obra_porcentaje',
            },
        ),
        migrations.CreateModel(
            name='Meta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.FloatField()),
                ('actividad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='meta_actividad', to='avance_de_obra.DActividad')),
            ],
            options={
                'db_table': 'avance_de_obra_meta',
                'permissions': (('can_see_meta', 'can see meta'),),
            },
        ),
        migrations.CreateModel(
            name='Linea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_linea', models.IntegerField()),
                ('cantidad', models.FloatField()),
                ('actividad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='linea_actividad', to='avance_de_obra.DActividad')),
                ('intervalo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='linea_intervalo', to='avance_de_obra.CIntervaloCronograma')),
            ],
            options={
                'db_table': 'avance_de_obra_linea',
                'permissions': (('can_see_linea', 'can see linea'),),
            },
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_linea', models.IntegerField()),
                ('comentario', models.TextField()),
                ('fecha', models.DateField(auto_now_add=True)),
                ('intervalo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='comentario_intervalo', to='avance_de_obra.CIntervaloCronograma')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='comentario_usuario', to='usuario.Usuario')),
            ],
            options={
                'db_table': 'avance_de_obra_comentario',
            },
        ),
    ]
