# Generated by Django 2.2.10 on 2023-01-20 22:35

from django.db import migrations, models
import django.db.models.deletion
import coasmedas.functions


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuario', '0001_initial'),
        ('tipo', '0001_initial'),
        ('estado', '0001_initial'),
        ('empresa', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AEscolaridad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'seguridad_social_escolaridad',
                'permissions': (('can_see_escolaridad', 'can see escolaridad'),),
            },
        ),
        migrations.CreateModel(
            name='AMatricula',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'seguridad_social_matricula',
                'permissions': (('can_see_matricula', 'can see matricula'),),
            },
        ),
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('soporte_tsa', models.BooleanField(default=False)),
                ('soporte_matricula', models.BooleanField(default=False)),
                ('hoja_de_vida', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'seguridad_social_cargo',
                'permissions': (('can_see_cargo_ss', 'can see cargo ss'),),
            },
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_nacimiento', models.DateField(null=True)),
                ('fecha_tsa', models.DateField(blank=True, null=True)),
                ('soporte_tsa', models.FileField(blank=True, null=True, upload_to=coasmedas.functions.RandomFileName('seguridad_social/soporte_tsa', 'ss'))),
                ('soporte_matricula', models.FileField(blank=True, null=True, upload_to=coasmedas.functions.RandomFileName('seguridad_social/soporte_matricula', 'ss'))),
                ('hoja_de_vida', models.FileField(blank=True, null=True, upload_to=coasmedas.functions.RandomFileName('seguridad_social/hoja_de_vida', 'ss'))),
                ('apto', models.BooleanField(default=False)),
                ('observacion', models.TextField(blank=True, null=True)),
                ('foto', models.ImageField(blank=True, null=True, upload_to=coasmedas.functions.RandomFileName('seguridad_social/empleado', 'ss'))),
                ('fecha_ingreso', models.DateField(blank=True, null=True)),
                ('tiene_licencia', models.BooleanField(default=False)),
                ('vencimiento_licencia', models.DateField(blank=True, null=True)),
                ('soporte_licencia', models.FileField(blank=True, null=True, upload_to=coasmedas.functions.RandomFileName('seguridad_social/licencia', 'ss'))),
                ('cargo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cargo_empleado', to='seguridad_social.Cargo')),
                ('contratista', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='empleado_empresa_contratista', to='empresa.Empresa')),
                ('empresa', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='empleado_empresa_creadora', to='empresa.Empresa')),
                ('escolaridad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='escolaridad_empleado', to='seguridad_social.AEscolaridad')),
                ('estado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='estado_empleado', to='estado.Estado')),
                ('matricula', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='matricula_empleado', to='seguridad_social.AMatricula')),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='usuario.Persona')),
                ('tipo_matricula', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tipo_matricula_empleado', to='tipo.Tipo')),
            ],
            options={
                'db_table': 'seguridad_social_empleado',
                'ordering': ['id'],
                'permissions': (('can_see_empleado', 'can see empleado'),),
            },
        ),
        migrations.CreateModel(
            name='Planilla',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano', models.IntegerField()),
                ('mes', models.IntegerField()),
                ('fecha_pago', models.DateField(blank=True, null=True)),
                ('soporte', models.FileField(blank=True, null=True, upload_to=coasmedas.functions.RandomFileName('seguridad_social/planillas', 'ss'))),
                ('fecha_limite', models.DateField(blank=True, null=True)),
                ('contratista', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='planilla_empresa_contratista', to='empresa.Empresa')),
                ('empresa', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='empresa_planilla', to='empresa.Empresa')),
            ],
            options={
                'db_table': 'seguridad_social_planilla',
                'ordering': ['-ano', '-mes'],
                'permissions': (('can_see_planilla', 'can see planilla'),),
            },
        ),
        migrations.CreateModel(
            name='Requerimientos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'seguridad_social_requerimiento',
                'permissions': (('can_see_requermientos', 'can see requerimientos'),),
            },
        ),
        migrations.CreateModel(
            name='RequerimientosValor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'seguridad_social_requerimiento_valor',
                'permissions': (('can_see_requermientos_valor', 'can see requermientos valor'),),
            },
        ),
        migrations.CreateModel(
            name='ZRequerimientosEmpleados',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empleado', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='requerimientos_empleados_empleado', to='seguridad_social.Empleado')),
                ('requerimiento', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='requeriemientos_requerimientos_empleado', to='seguridad_social.Requerimientos')),
                ('requerimiento_valor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='seguridad_social.RequerimientosValor')),
            ],
            options={
                'db_table': 'seguridad_social_requerimientos_empleados',
                'permissions': (('can_see_requermientos_empleados', 'can see requermientos empleados'),),
            },
        ),
        migrations.CreateModel(
            name='PlanillaEmpleado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tiene_pago', models.BooleanField(default=False)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='planilla_empleado_empleado', to='seguridad_social.Empleado')),
                ('planilla', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='planilla_empleado_planilla', to='seguridad_social.Planilla')),
            ],
            options={
                'db_table': 'seguridad_social_planilla_empleado',
                'permissions': (('can_see_planilla_empleado', 'can see planilla empleado'),),
            },
        ),
        migrations.CreateModel(
            name='Novedad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(null=True)),
                ('descripcion', models.CharField(blank=True, max_length=300, null=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('empleado', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='empleado_novedad', to='seguridad_social.Empleado')),
                ('estado', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='estado_novedad', to='estado.Estado')),
            ],
            options={
                'db_table': 'seguridad_social_novedad',
                'permissions': (('can_see_novedad', 'can see novedad'),),
            },
        ),
        migrations.CreateModel(
            name='EmpresaPermiso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='empresa_permiso_empresa', to='empresa.Empresa')),
                ('empresa_acceso', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='empresa_permiso_empresa_acceso', to='empresa.Empresa')),
            ],
            options={
                'db_table': 'seguridad_social_empresa_permiso',
                'permissions': (('can_see_empresa_permiso', 'can see empresa permiso'),),
            },
        ),
        migrations.CreateModel(
            name='CorreoContratista',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correo', models.CharField(max_length=100)),
                ('contratista', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='empleado_correo_contratista', to='empresa.Empresa')),
            ],
            options={
                'db_table': 'seguridad_social_correo_contratista',
                'permissions': (('can_see_correo_contratista', 'can see correo contratista'),),
                'unique_together': {('contratista', 'correo')},
            },
        ),
    ]
