from django.conf.urls import url

from . import views


urlpatterns = [
  	url(r'^hitos/$', views.avance_de_obra_grafico, name='avance_de_obra_grafico.hitos'),
    url(r'^eliminar_esquema/$', views.eliminar_esquema, name='avance_de_obra_grafico.eliminar_esquema'),
    url(r'^actividades/(?P<id_esquema>[0-9]+)/$', views.actividades, name='avance_de_obra_grafico.actividades'),
    url(r'^presupuesto/$', views.presupuesto, name='avance_de_obra_grafico.presupuesto'),
    url(r'^presupuesto_encabezado/(?P<id_proyecto>[0-9]+)/$', views.presupuesto_encabezado, name='avance_de_obra_grafico.presupuesto_encabezado'),
    url(r'^eliminar_id_presupuesto/$', views.eliminar_id_presupuesto, name='avance_de_obra_grafico.eliminar_id_presupuesto'),
    url(r'^presupuesto_detalle/(?P<id_presupuesto>[0-9]+)/$', views.presupuesto_detalle, name='avance_de_obra_grafico.presupuesto_detalle'),
    url(r'^descargar_plantilla_presupuesto/$', views.descargar_plantilla_presupuesto, name='avance_de_obra_grafico.descargar_plantilla_presupuesto'),
    url(r'^guardar_presupuesto_archivo/$', views.guardar_presupuesto_archivo, name='avance_de_obra_grafico.guardar_presupuesto_archivo'),
    url(r'^presupuesto_vista_detalle/(?P<id_presupuesto>[0-9]+)/$', views.presupuesto_vista_detalle, name='avance_de_obra_grafico.presupuesto_vista_detalle'),
    url(r'^actualizar_cantidad/$', views.actualizar_cantidad, name='avance_de_obra_grafico.actualizar_cantidad'),
    url(r'^cierre_presupuesto/$', views.cierre_presupuesto, name='avance_de_obra_grafico.cierre_presupuesto'),
    url(r'^alcance/$', views.alcance, name='avance_de_obra_grafico.alcance'),
    url(r'^apoyo/(?P<id_presupuesto>[0-9]+)/$', views.apoyo, name='avance_de_obra_grafico.apoyo'),
    url(r'^descargar_plantilla_apoyo/$', views.descargar_plantilla_apoyo, name='avance_de_obra_grafico.descargar_plantilla_apoyo'),
    url(r'^guardar_apoyo_archivo/$', views.guardar_apoyo_archivo, name='avance_de_obra_grafico.guardar_apoyo_archivo'),
    url(r'^cantidad_apoyo/(?P<id_presupuesto>[0-9]+)/$', views.cantidad_apoyo, name='avance_de_obra_grafico.cantidad_apoyo'),
    url(r'^descargar_plantilla_cantidadApoyo/$', views.descargar_plantilla_cantidadApoyo, name='avance_de_obra_grafico.descargar_plantilla_cantidadApoyo'),
    url(r'^guardar_cantidadApoyo_archivo/$', views.guardar_cantidadApoyo_archivo, name='avance_de_obra_grafico.guardar_cantidadApoyo_archivo'),
    url(r'^cantidad_apoyo_id/(?P<id_presupuesto>[0-9]+)/(?P<id_detalle>[0-9]+)/$', views.cantidad_apoyo_id, name='avance_de_obra_grafico.cantidad_apoyo_id'),
    url(r'^guardar_cantidad_apoyo/$', views.guardar_cantidad_apoyo, name='avance_de_obra_grafico.guardar_cantidad_apoyo'),
    url(r'^cronograma/$', views.cronograma, name='avance_de_obra_grafico.cronograma'),
    url(r'^cronograma_proyecto/(?P<id_presupuesto>[0-9]+)/(?P<id_proyecto>[0-9]+)/$', views.cronograma_proyecto, name='avance_de_obra_grafico.cronograma_proyecto'),
    url(r'^eliminar_id_cronograma/$', views.eliminar_id_cronograma, name='avance_de_obra_grafico.eliminar_id_cronograma'),
    url(r'^actividades_lectura/(?P<id_presupuesto>[0-9]+)/(?P<id_proyecto>[0-9]+)/(?P<id_esquema>[0-9]+)/$', views.actividades_lectura, name='avance_de_obra_grafico.actividades_lectura'),
    url(r'^cantidad_ejecutar/(?P<id_presupuesto>[0-9]+)/(?P<id_proyecto>[0-9]+)/$', views.cantidad_ejecutar, name='avance_de_obra_grafico.cantidad_ejecutar'),
    url(r'^linea_base/(?P<id_presupuesto>[0-9]+)/(?P<id_proyecto>[0-9]+)/(?P<id_cronograma>[0-9]+)/$', views.linea_base, name='avance_de_obra_grafico.linea_base'),
    url(r'^descargar_plantilla_lineabase/$', views.descargar_plantilla_lineabase, name='avance_de_obra_grafico.descargar_plantilla_lineabase'),
    url(r'^guardar_lineabase_fecha_archivo/$', views.guardar_lineabase_fecha_archivo, name='avance_de_obra_grafico.guardar_lineabase_fecha_archivo'),
    url(r'^guardar_linea/$', views.guardar_linea, name='avance_de_obra_grafico.guardar_linea'),
    url(r'^programacion/(?P<id_presupuesto>[0-9]+)/(?P<id_proyecto>[0-9]+)/(?P<id_cronograma>[0-9]+)/$', views.programacion, name='avance_de_obra_grafico.programacion'),
    url(r'^avance_obra/(?P<id_presupuesto>[0-9]+)/(?P<id_proyecto>[0-9]+)/(?P<id_cronograma>[0-9]+)/$', views.avance_obra, name='avance_de_obra_grafico.avance_obra'),
    url(r'^clonacion_esquema/$', views.clonacion_esquema, name='avance_de_obra_grafico.clonacion_esquema'),
    url(r'^informe_cantidad_apoyo/$', views.informe_cantidad_apoyo, name='avance_de_obra_grafico.informe_cantidad_apoyo'),
    url(r'^guardar_cambio_cantidades/$', views.guardar_cambio_cantidades, name='avance_de_obra_grafico.guardar_cambio_cantidades'),
    url(r'^guardar_nodos_nuevos/$', views.guardar_nodos_nuevos, name='avance_de_obra_grafico.guardar_nodos_nuevos'),
    url(r'^eliminar_cambio/$', views.eliminar_cambio, name='avance_de_obra_grafico.eliminar_cambio'),
    url(r'^guardar_nodo_eliminacion/$', views.guardar_nodo_eliminacion, name='avance_de_obra_grafico.guardar_nodo_eliminacion'),
    url(r'^cambio/(?P<id_presupuesto>[0-9]+)/(?P<id_proyecto>[0-9]+)/(?P<id_cronograma>[0-9]+)/$', views.cambio, name='avance_de_obra_grafico.cambio'),
    url(r'^detalle_cambio/(?P<id_proyecto>[0-9]+)/(?P<id_cronograma>[0-9]+)/(?P<id_cambio>[0-9]+)/$', views.detalle_cambio, name='avance_de_obra_grafico.detalle_cambio'),
    url(r'^consultar_detalle_cambio/$', views.consultar_detalle_cambio, name='avance_de_obra_grafico.consultar_detalle_cambio'),
    url(r'^guardar_nuevas_cantidades/$', views.guardar_nuevas_cantidades, name='avance_de_obra_grafico.guardar_nuevas_cantidades'),
    url(r'^cambio_estado/$', views.cambio_estado, name='avance_de_obra_grafico.cambio_estado'),
    url(r'^consultar_detalle_modificacion/$', views.consultar_detalle_modificacion, name='avance_de_obra_grafico.consultar_detalle_modificacion'),
    url(r'^guardar_modificacion/$', views.guardar_modificacion, name='avance_de_obra_grafico.guardar_modificacion'),
    url(r'^consultar_avance_obra/$', views.consultar_avance_obra, name='avance_de_obra_grafico.consultar_avance_obra'),
    url(r'^regla_estado/(?P<id_esquema>[0-9]+)/$', views.regla_estado, name='avance_de_obra_grafico.regla_estado'),
    url(r'^eliminar_id_regla_estado/$', views.eliminar_id_regla_estado, name='avance_de_obra_grafico.eliminar_id_regla_estado'),
    url(r'^informe_presupuesto/$', views.informe_presupuesto, name='avance_de_obra_grafico.informe_presupuesto'),
    url(r'^eliminar_id_apoyo/$', views.eliminar_id_apoyo, name='avance_de_obra_grafico.eliminar_id_apoyo'),
    url(r'^digrama_grahm/(?P<id_presupuesto>[0-9]+)/$', views.digrama_grahm, name='avance_de_obra_grafico.digrama_grahm'),
    url(r'^eliminar_diagrama/$', views.eliminar_diagrama, name='avance_de_obra_grafico.eliminar_diagrama'),
    url(r'^informe_diagrama/$', views.informe_diagrama, name='avance_de_obra_grafico.informe_diagrama'),
    url(r'^eliminar_id_nodo_destino/$', views.eliminar_id_nodo_destino, name='avance_de_obra_grafico.eliminar_id_nodo_destino'),
    url(r'^guardar_cambio_detalle/$', views.guardar_cambio_detalle, name='avance_de_obra_grafico.guardar_cambio_detalle'),
    url(r'^grafico/(?P<id_presupuesto>[0-9]+)/(?P<id_proyecto>[0-9]+)/(?P<id_cronograma>[0-9]+)/$', views.grafico, name='avance_de_obra_grafico.grafico'),
    url(r'^consultar_graficos/$', views.consultar_graficos, name='avance_de_obra_grafico.consultar_graficos'),
    url(r'^apoyo_sin_gps/(?P<id_presupuesto>[0-9]+)/$', views.apoyo_sin_gps, name='avance_de_obra_grafico.apoyo_sin_gps'),
    url(r'^eliminar_apoyos/$', views.eliminar_apoyos, name='avance_de_obra_grafico.eliminar_apoyos'),
    url(r'^descargar_plantilla_apoyo_sinposicion/$', views.descargar_plantilla_apoyo_sinposicion, name='avance_de_obra_grafico.descargar_plantilla_apoyo_sinposicion'),
    url(r'^guardar_apoyo_archivo_sinposicion/$', views.guardar_apoyo_archivo_sinposicion, name='avance_de_obra_grafico.guardar_apoyo_archivo_sinposicion'),
    url(r'^avance_obra_sin_gps/(?P<id_presupuesto>[0-9]+)/(?P<id_proyecto>[0-9]+)/(?P<id_cronograma>[0-9]+)/$', views.avance_obra_sin_gps, name='avance_de_obra_grafico.avance_obra_sin_gps'),
    
]