# Generated by Django 2.2.10 on 2023-01-30 15:27

from django.db import migrations, models
import coasmedas.functions


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GestionOp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=100, unique=True)),
                ('fecha_registro', models.DateField(auto_now_add=True)),
                ('fecha_pago', models.DateField(blank=True, null=True)),
                ('soporte', models.FileField(blank=True, null=True, upload_to=coasmedas.functions.RandomFileName('seguimiento_factura/gestio_op', 'fac'))),
                ('pagado_recursos_propios', models.BooleanField(default=False)),
                ('soporte_pago', models.FileField(blank=True, null=True, upload_to=coasmedas.functions.RandomFileName('seguimiento_factura/gestio_op', 'soporte_pago'))),
                ('facturas_anuladas', models.TextField(blank=True)),
                ('anulado', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'seguimiento_factura_gestion_op',
                'permissions': (('can_see_seguimiento_factura', 'can_see_seguimiento_factura'), ('can_see_seguimiento_factura_por_contabilizar', 'can_see_seguimiento_factura_por_contabilizar'), ('can_see_seguimiento_factura_habilitar_tes_op', 'can_see_seguimiento_factura_habilitar_tes_op'), ('can_see_seguimiento_factura_test_op', 'can_see_seguimiento_factura_test_op'), ('can_see_seguimiento_factura_recursos_propios', 'can_see_seguimiento_factura_recursos_propios'), ('can_see_seguimiento_factura_por_pagar', 'can_see_seguimiento_factura_por_pagar'), ('can_see_seguimiento_factura_consultar_pago', 'can_see_seguimiento_factura_consultar_pago'), ('can_see_seguimiento_factura_administrador_cuenta', 'can_see_seguimiento_factura_administrador_cuenta')),
            },
        ),
    ]
