# Generated by Django 2.2.10 on 2023-01-20 22:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tipo', '0001_initial'),
        ('usuario', '0001_initial'),
        ('contrato', '0001_initial'),
        ('proyecto', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Archivo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=250)),
                ('padre', models.IntegerField(blank=True)),
                ('destino', models.FileField(blank=True, null=True, upload_to='mi_nube')),
                ('eliminado', models.BooleanField(default=False)),
                ('peso', models.FloatField(blank=True)),
                ('fechaModificado', models.DateTimeField(auto_now_add=True)),
                ('contrato', models.ManyToManyField(blank=True, related_name='fk_Contrato_Archivo', to='contrato.Contrato')),
                ('propietario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fk_Archivo_propietario', to='usuario.Usuario')),
                ('proyecto', models.ManyToManyField(blank=True, related_name='fk_Proyecto_Archivo', to='proyecto.Proyecto')),
                ('tipoArchivo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fk_Tipo_Archivo', to='tipo.Tipo')),
                ('usuarioModificado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fk_usuarioModificado_Archivo', to='usuario.Usuario')),
            ],
            options={
                'permissions': (('can_see_Archivo', 'can_see_Archivo'),),
                'unique_together': {('padre', 'nombre', 'tipoArchivo', 'propietario')},
            },
        ),
        migrations.CreateModel(
            name='ArchivoUsuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('escritura', models.BooleanField(default=False)),
                ('archivo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fk_Archivo_ArchivoUsuario', to='mi_nube.Archivo')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fk_Usuario_ArchivoUsuario', to='usuario.Usuario')),
            ],
            options={
                'permissions': (('can_see_ArchivoUsuario', 'can_see_ArchivoUsuario'),),
                'unique_together': {('usuario', 'archivo')},
            },
        ),
    ]
