# Generated by Django 2.2.10 on 2023-01-30 15:35

from django.db import migrations, models
import django.db.models.deletion
import coasmedas.functions


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuario', '0001_initial'),
        ('contrato', '0001_initial'),
        ('parametrizacion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificacion', models.CharField(blank=True, max_length=50, null=True)),
                ('serial_placa', models.CharField(blank=True, max_length=50, null=True)),
                ('descripcion', models.CharField(max_length=150)),
                ('valor_compra', models.BigIntegerField(blank=True, null=True)),
                ('vida_util_dias', models.IntegerField()),
                ('periodicidad_mantenimiento', models.IntegerField(blank=True, null=True)),
                ('debaja', models.BooleanField(default=False)),
                ('motivo_debaja', models.CharField(blank=True, max_length=150, null=True)),
                ('soportedebaja', models.FileField(blank=True, null=True, upload_to=coasmedas.functions.RandomFileName('activos', 'act'))),
                ('fecha_baja', models.DateField(blank=True, null=True)),
                ('fecha_alta', models.DateField()),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='activo_contrato', to='contrato.Contrato')),
                ('responsable', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='activo_funcionario', to='parametrizacion.Funcionario')),
            ],
            options={
                'db_table': 'activos_activo',
                'permissions': (('can_see_activos', 'can see activos'),),
            },
        ),
        migrations.CreateModel(
            name='Activo_atributo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.CharField(max_length=30)),
                ('activo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='activoatributo_activo', to='activos.Activo')),
            ],
            options={
                'db_table': 'activos_activo_atributo',
            },
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'activos_categoria',
            },
        ),
        migrations.CreateModel(
            name='Mantenimiento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('hora', models.TimeField(blank=True, null=True)),
                ('observaciones', models.CharField(blank=True, max_length=50, null=True)),
                ('activo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mantenimiento_activo', to='activos.Activo')),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='contrato.Contrato')),
            ],
            options={
                'db_table': 'activos_mantenimiento',
            },
        ),
        migrations.CreateModel(
            name='Tipo_Activo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('prefijo', models.CharField(blank=True, max_length=10, null=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tipoactivo_categoria', to='activos.Categoria')),
            ],
            options={
                'db_table': 'activos_tipo',
            },
        ),
        migrations.CreateModel(
            name='Soporte_mantenimiento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=30, null=True)),
                ('archivo', models.FileField(upload_to=coasmedas.functions.RandomFileName('activos/soporte_mantenimiento', 'sop_man'))),
                ('mantenimiento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='soportemantenimiento_mantenimiento', to='activos.Mantenimiento')),
            ],
            options={
                'db_table': 'activos_soporte_mantenimiento',
            },
        ),
        migrations.CreateModel(
            name='Motivo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('tipo_activo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='motivo_tipoactivo', to='activos.Tipo_Activo')),
            ],
            options={
                'db_table': 'activos_motivo',
            },
        ),
        migrations.AddField(
            model_name='mantenimiento',
            name='motivo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mantenimiento_motivo', to='activos.Motivo'),
        ),
        migrations.CreateModel(
            name='Atributo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('requiere_soporte', models.BooleanField(default=False)),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='atributo_tipo', to='activos.Tipo_Activo')),
            ],
            options={
                'db_table': 'activos_atributo',
            },
        ),
        migrations.CreateModel(
            name='Activo_persona',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='activopersona_activo', to='activos.Activo')),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='activopersona_persona', to='usuario.Persona')),
            ],
            options={
                'db_table': 'activos_activo_persona',
            },
        ),
        migrations.CreateModel(
            name='Activo_atributo_soporte',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('documento', models.FileField(upload_to=coasmedas.functions.RandomFileName('activos/atributo_soporte', 'atri_sop'))),
                ('activo_atributo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='activoatributosoporte_activoatributo', to='activos.Activo_atributo')),
            ],
            options={
                'db_table': 'activos_activo_atributo_soporte',
            },
        ),
        migrations.AddField(
            model_name='activo_atributo',
            name='atributo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='activoatributo_atributo', to='activos.Atributo'),
        ),
        migrations.AddField(
            model_name='activo',
            name='tipo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='activo_tipoactivo', to='activos.Tipo_Activo'),
        ),
        migrations.CreateModel(
            name='Activo_gps',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=30, null=True)),
                ('longitud', models.CharField(max_length=50)),
                ('latitud', models.CharField(max_length=50)),
                ('activo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='activogps_activo', to='activos.Activo')),
            ],
            options={
                'db_table': 'activos_gps',
                'unique_together': {('activo', 'nombre')},
            },
        ),
    ]
