# Generated by Django 2.2.10 on 2023-01-30 15:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contrato', '0001_initial'),
        ('empresa', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InformeMME',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(blank=True, null=True)),
                ('consecutivo', models.BigIntegerField()),
                ('soporte', models.FileField(blank=True, null=True, upload_to='informe_mme/soporte')),
                ('ano', models.IntegerField()),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fk_informe_contrato', to='contrato.Contrato')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fk_informe_empresa', to='empresa.Empresa')),
            ],
            options={
                'db_table': 'informe_mme',
                'permissions': (('can_see_informemme', 'can_see_informemme'),),
                'unique_together': {('empresa', 'consecutivo', 'ano')},
            },
        ),
        migrations.CreateModel(
            name='InformeConsecutivo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano', models.IntegerField()),
                ('numero', models.IntegerField()),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='informeconsecutivo_empresa', to='empresa.Empresa')),
            ],
            options={
                'permissions': (('can_see_InformeConsecutivo', 'can_see_InformeConsecutivo'),),
                'unique_together': {('empresa', 'ano')},
            },
        ),
    ]
