# Generated by Django 2.2.10 on 2023-01-30 15:31

from django.db import migrations, models
import django.db.models.deletion
import sinin4.functions


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('estado', '0001_initial'),
        ('tipo', '0001_initial'),
        ('proyecto', '0001_initial'),
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NoConformidad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion_no_corregida', models.CharField(max_length=4000)),
                ('descripcion_corregida', models.CharField(blank=True, max_length=4000, null=True)),
                ('foto_no_corregida', models.ImageField(blank=True, null=True, upload_to=sinin4.functions.RandomFileName('no_conformidad/foto_no_corregida', 'no_cf_no_crr'))),
                ('foto_no_corregida2', models.ImageField(blank=True, null=True, upload_to=sinin4.functions.RandomFileName('no_conformidad/foto_no_corregida', 'no_cf_no_crr'))),
                ('foto_no_corregida3', models.ImageField(blank=True, null=True, upload_to=sinin4.functions.RandomFileName('no_conformidad/foto_no_corregida', 'no_cf_no_crr'))),
                ('foto_corregida', models.ImageField(blank=True, null=True, upload_to=sinin4.functions.RandomFileName('no_conformidad/foto_corregida', 'no_cf_crr'))),
                ('foto_corregida2', models.ImageField(blank=True, null=True, upload_to=sinin4.functions.RandomFileName('no_conformidad/foto_corregida', 'no_cf_crr'))),
                ('foto_corregida3', models.ImageField(blank=True, null=True, upload_to=sinin4.functions.RandomFileName('no_conformidad/foto_corregida', 'no_cf_crr'))),
                ('fecha_no_corregida', models.DateField(blank=True, null=True)),
                ('fecha_corregida', models.DateField(blank=True, null=True)),
                ('terminada', models.BooleanField(default=False)),
                ('estructura', models.CharField(max_length=1000)),
                ('primer_correo', models.DateField(blank=True, null=True)),
                ('segundo_correo', models.DateField(blank=True, null=True)),
                ('tercer_correo', models.DateField(blank=True, null=True)),
                ('detectada', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fk_no_conformidad_detectada_usuario', to='usuario.Usuario')),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fk_no_conformidad_estado', to='estado.Estado')),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fk_no_conformidad_proyecto', to='proyecto.Proyecto')),
                ('tipo', models.ForeignKey(blank=True, limit_choices_to=models.Q(app='no_conformidad'), null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fk_no_conformidad_tipo', to='tipo.Tipo')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fk_no_conformidad_usuario', to='usuario.Usuario')),
                ('valoracion', models.ForeignKey(blank=True, limit_choices_to=models.Q(app='no_conformidad_valoracion'), null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fk_no_conformidad_valoracion', to='tipo.Tipo')),
            ],
            options={
                'db_table': 'no_conformidad',
                'permissions': (('can_see_no_conformidad', 'can see no_conformidad'),),
            },
        ),
    ]
