# Generated by Django 2.2.10 on 2023-01-30 15:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contrato', '0001_initial'),
        ('proyecto', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Informe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
            options={
                'permissions': (('can_see_informe_dinamico', 'can_see_informe_dinamico'),),
            },
        ),
        migrations.CreateModel(
            name='Proyecto_Actividad_contrato',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.CharField(blank=True, max_length=4000, null=True)),
                ('actividad', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='contrato.Actividad')),
                ('proyecto', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='proyecto.Proyecto')),
            ],
            options={
                'db_table': 'proyecto_actividad_contrato',
                'unique_together': {('proyecto', 'actividad')},
            },
        ),
    ]
